<div class="container_12">	
	<div class="grid_12">
		<?php echo $this->element->first ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_12">
		<?php echo $this->element->last ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_12">
		<?php echo $this->element->homePhone ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_12">
		<?php echo $this->element->workPhone ?>
	</div>
	
	<div class="clear"></div>
	
	<?php echo $this->element->siteId ?>
	<?php echo $this->element->studentId ?>
</div>