<?php $cellId = "Airway_" . $this->airway->id; ?>
<? $am = ($this->airway->airway_management) ? true : false; ?>

<tr id="<?= $cellId ?>">
<?php
if ($this->airway->soft_deleted) {
    echo "<td colspan='4' class='undo'>Airway #" . $this->airway->id . " successfully deleted. <a id='undo-delete-$cellId' href='#' onclick='undoDeleteSkill(\"$cellId\"); return false;'>Undo!</a></td>";
    $elementStyle = "style='display:none;'";
}
?>
    <td <?= $elementStyle ?> class='procedure-grabby-column'><img src="/images/icons/wide_grabby.png" class='grabby-icon' title='Click and drag to reorder' /></td>
    <td <?= $elementStyle ?> class='procedure-icon-column'>
        <img class='small-skill-icon' <?= ($am) ? "style='width:35px;'" : ""; ?> src='/images/icons/<?= ($am) ? "airway_management.png" : "airway_gray.png"; ?>'>
    </td>
    <td <?= $elementStyle ?> class='procedure-description-column' onclick="loadAirwayModal(<?= $this->airway->id ?>);"><?= $this->airway->getProcedureText(); ?></td>
    <td <?= $elementStyle ?> class='procedure-tools-column'>
        <?= $this->skillEvalHookHelper('airway', $this->airway);?>
        <a href="#" class="duplicate-skill" onclick="duplicateSkill(<?= $this->airway->id ?>, 'Airway'); return false;"><img class="small-icon" title="duplicate skill" src="/images/icons/duplicate.png"></a>
        <a href="#" class="delete-skill" skillId="<?= $cellId ?>" title="delete skill">
            <img class="tiny-icon square" src="/images/icons/delete.svg" alt="delete skill">
        </a>
    </td>
</tr>