
<div class="container_12">
	
	<div class="grid_12">
		<?php echo $this->element->rhythmPerformed ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?= $this->element->rhythm ?>
	</div>
	
	<div class="grid_4">
		<br /><?= $this->element->twelveLead ?>
	</div>

	<div class="clear"></div>

	<div class="grid_6">
		<?php echo $this->element->ectopies ?>
	</div>
	
	<div class="clear"></div>
		
	<br />
	<br />
	<br />
	
	
	<div class="grid_12">
		<?php echo $this->element->cardiacPerformed ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->cardiacProcedure ?>
	</div>
	
	<div class="clear"></div>

	
	<div class="grid_6">
		<?php echo $this->element->procedureMethod ?>
		<?php echo $this->element->pacingMethod ?>
	</div>
	
	<div class="clear"></div>
	<?php echo $this->element->cardiacId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>
