<div class="container_12">
	
	<div class="grid_12">
		<?php echo $this->element->ivPerformed ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->ivProcedure ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->ivSize ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->ioSize ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->site ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->fluid ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->ivAttempts ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->ivSuccess ?>
	</div>
	
	<div class="clear"></div>
	<?php echo $this->element->ivId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>


<div class="iv-modal-buttons">
	<button id="cancel-iv-modal">Cancel</button>
	<span class="green-buttons"><button id="save-iv-modal">Save</button></span>
</div>