<? if ($this->shift->isFuture()) { ?>
	<div class='grid_12 island withTopMargin'>
		You can't document skills or patient care for a shift that hasn't happened yet. Check back on the day of the shift.
	</div>
<? } else { ?>
	<? if ($this->isBlankState && $video = $this->youtubeVideo("-J9IR3H7pkM", "my-shift-blank-state.phtml", 500, 300)) {
		echo "<div class='grid_12 island withTopMargin'>$video</div>";
	} ?>

	<? if ($this->showPracticeSkills) {
        if (!$this->isInstructor) {
            echo '<div class="grid_12 island withTopMargin" style="overflow:visible;">';
            echo '<div id="lab-skills-widgets">' . $this->sectionHelper('lab-skills-widgets', 450) . '</div>';
            echo '</div>';
        }
		echo $this->practiceSkillWidget($this->shift, $this->labPartnerShifts);
	} ?>

	<div class='grid_12 island withTopMargin'>
		<?= $this->runList($this->shift, $this->runs, $this->isInstructor, $this->shift->type); ?>
	</div>

    <div class='grid_12 island withTopMargin'>
        <?= $this->shiftAttachmentList($this->shift, $this->attachments, $this->isInstructor, $this->attachmentsRemaining) ?>
    </div>

	<? if ($this->showQuickAddSkills) { ?>
		<div class='grid_12 island withTopMargin'>
			<h2 class="section-header">Quick Add Skills</h2>
				<p>Use Quick Add Skills when you don't have any patient information to enter, but still want to get credit for the skills you performed.</p>
				<a id="add-skills-link" href="#">
                    <img id="arrow" style="width:.75em;" src="/images/arrow_right.png">
                    <span id="add-skills-text">Show skills</span>
                </a>
		
			<div class="clear"></div>
			<?= $this->interventionList(null, $this->shift->id, false); ?>
		</div>
	<? } ?>
<? } ?>

<?= $this->airwayModal ?>
<?= $this->cardiacModal ?>
<?= $this->ivModal ?>
<?= $this->medModal ?>
<?= $this->otherModal ?>
<?= $this->vitalModal ?>