<div class="container_12">
	
	<div class="grid_12">
		<?php echo $this->element->otherPerformed ?>
	</div>
	
	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->otherProcedure ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->otherSize ?>
	</div>

	<div class="clear"></div>
	
	<div class="grid_6">
		<?php echo $this->element->otherAttempts ?>
	</div>
	
	<div class="grid_6">
		<?php echo $this->element->otherSuccess ?>
	</div>
	
	<div class="clear"></div>
	
	<?php echo $this->element->otherId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>