<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

?>

<style>
	.welcome-header{
		font-family: tahoma;
		font-size: 14pt;
		font-weight: 900;
		color: #707070;
	}
</style>

<span class='welcome-header'>Welcome!  It looks like you're ready to document shifts or maybe some lab practice.  Here's a video that will help you get started.</span>
<br />
<br />


<div class='grid_12' style='text-align: center'>

	<?php echo $this->video; ?>	
</div>
