<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProgramLegacy extends \User\Entity\ProgramLegacy implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'abbreviation', 'class_size', 'website', 'active', 'created', 'profession', 'program_settings', 'useDNADFlag', 'entityRepository', 'address', 'address2', 'address3', 'city', 'state', 'zip', 'country', 'phone', 'fax', 'program_contact', 'contact_email', 'billing_email', 'billing_contact', 'billing_address', 'billing_address2', 'billing_address3', 'billing_city', 'billing_state', 'billing_zip', 'billing_country', 'billing_phone', 'billing_fax', 'referral', 'ref_description', 'program_types', 'accredited', 'coaemsp_program_id', 'year_accredited', 'can_students_create_field', 'can_students_create_clinical', 'student_view_full_calendar', 'can_students_pick_field', 'can_students_pick_clinical', 'can_students_pick_lab', 'can_students_create_lab', 'allow_absent_with_permission', 'include_narrative', 'send_late_shift_emails', 'send_critical_thinking_emails', 'late_field_deadline', 'late_clinical_deadline', 'late_lab_deadline', 'customer_name', 'customer_id', 'requires_po', 'product_code_id', 'order_permission', 'serialNumbers', 'reports', 'program_site_associations', 'site_shares', 'site_staff_members', 'program_base_associations', 'program_preceptor_associations', 'med_types', 'lab_assessments', 'goalsets', 'practice_definitions', 'practice_categories', 'airway_procedures', 'cardiac_procedures', 'iv_procedures', 'other_procedures', 'requirement_notifications', 'program_type', 'class_start_dates', 'field_trade_code', 'field_drop_code', 'use_scheduler', 'clinical_trade_code', 'clinical_drop_code', 'lab_trade_code', 'lab_drop_code', 'requirements', 'use_beta', 'scheduler_beta'];
        }

        return ['__isInitialized__', 'id', 'name', 'abbreviation', 'class_size', 'website', 'active', 'created', 'profession', 'program_settings', 'useDNADFlag', 'entityRepository', 'address', 'address2', 'address3', 'city', 'state', 'zip', 'country', 'phone', 'fax', 'program_contact', 'contact_email', 'billing_email', 'billing_contact', 'billing_address', 'billing_address2', 'billing_address3', 'billing_city', 'billing_state', 'billing_zip', 'billing_country', 'billing_phone', 'billing_fax', 'referral', 'ref_description', 'program_types', 'accredited', 'coaemsp_program_id', 'year_accredited', 'can_students_create_field', 'can_students_create_clinical', 'student_view_full_calendar', 'can_students_pick_field', 'can_students_pick_clinical', 'can_students_pick_lab', 'can_students_create_lab', 'allow_absent_with_permission', 'include_narrative', 'send_late_shift_emails', 'send_critical_thinking_emails', 'late_field_deadline', 'late_clinical_deadline', 'late_lab_deadline', 'customer_name', 'customer_id', 'requires_po', 'product_code_id', 'order_permission', 'serialNumbers', 'reports', 'program_site_associations', 'site_shares', 'site_staff_members', 'program_base_associations', 'program_preceptor_associations', 'med_types', 'lab_assessments', 'goalsets', 'practice_definitions', 'practice_categories', 'airway_procedures', 'cardiac_procedures', 'iv_procedures', 'other_procedures', 'requirement_notifications', 'program_type', 'class_start_dates', 'field_trade_code', 'field_drop_code', 'use_scheduler', 'clinical_trade_code', 'clinical_drop_code', 'lab_trade_code', 'lab_drop_code', 'requirements', 'use_beta', 'scheduler_beta'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (! $this->__isInitialized__) {
            $this->__initializer__ = function (ProgramLegacy $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbbreviation()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbbreviation', []);

        return parent::getAbbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbbreviation($abbreviation)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbbreviation', [$abbreviation]);

        return parent::setAbbreviation($abbreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function generateAbbreviation()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateAbbreviation', []);

        return parent::generateAbbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassSize()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassSize', []);

        return parent::getClassSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassSize($class_size)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassSize', [$class_size]);

        return parent::setClassSize($class_size);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function set_profession($value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_profession', [$value]);

        return parent::set_profession($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession(\User\Entity\Profession $profession)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', []);

        return parent::setCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramSettings()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramSettings', []);

        return parent::getProgramSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function get_possible_graduation_years($null_value = true)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_possible_graduation_years', [$null_value]);

        return parent::get_possible_graduation_years($null_value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_possible_graduations_years_from_sn($null_value = true)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_possible_graduations_years_from_sn', [$null_value]);

        return parent::get_possible_graduations_years_from_sn($null_value);
    }

    /**
     * {@inheritDoc}
     */
    public function createDemoAccount($instructor)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDemoAccount', [$instructor]);

        return parent::createDemoAccount($instructor);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setUUID($uuid = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUUID', [$uuid]);

        return parent::setUUID($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUUID()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUUID', []);

        return parent::getUUID();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityRepository()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityRepository', []);

        return parent::getEntityRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function save($flush = true)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', [$flush]);

        return parent::save($flush);
    }

    /**
     * {@inheritDoc}
     */
    public function delete($flush = true)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', [$flush]);

        return parent::delete($flush);
    }

    /**
     * {@inheritDoc}
     */
    public function flush()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'flush', []);

        return parent::flush();
    }

    /**
     * {@inheritDoc}
     */
    public function isDatabaseField($field)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDatabaseField', [$field]);

        return parent::isDatabaseField($field);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldmap()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldmap', []);

        return parent::getFieldmap();
    }

    /**
     * {@inheritDoc}
     */
    public function isUsingDNAD()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUsingDNAD', []);

        return parent::isUsingDNAD();
    }

    /**
     * {@inheritDoc}
     */
    public function getQueryBuilder()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQueryBuilder', []);

        return parent::getQueryBuilder();
    }

    /**
     * {@inheritDoc}
     */
    public function deleteGroup($group)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteGroup', [$group]);

        return parent::deleteGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortName', []);

        return parent::getShortName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', []);

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', [$address2]);

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress3()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress3', []);

        return parent::getAddress3();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress3($address3)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress3', [$address3]);

        return parent::setAddress3($address3);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramContactName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramContactName', []);

        return parent::getProgramContactName();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramContact()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramContact', []);

        return parent::getProgramContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramContactUser()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramContactUser', []);

        return parent::getProgramContactUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactEmail()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactEmail', []);

        return parent::getContactEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactEmail($contact_email)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactEmail', [$contact_email]);

        return parent::setContactEmail($contact_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingEmail()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingEmail', []);

        return parent::getBillingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingEmail($billing_email)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingEmail', [$billing_email]);

        return parent::setBillingEmail($billing_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingContact()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingContact', []);

        return parent::getBillingContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingContact($billing_contact)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingContact', [$billing_contact]);

        return parent::setBillingContact($billing_contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress($billing_address)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', [$billing_address]);

        return parent::setBillingAddress($billing_address);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress2()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress2', []);

        return parent::getBillingAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress2($billing_address2)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress2', [$billing_address2]);

        return parent::setBillingAddress2($billing_address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress3()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress3', []);

        return parent::getBillingAddress3();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress3($billing_address3)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress3', [$billing_address3]);

        return parent::setBillingAddress3($billing_address3);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCity()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCity', []);

        return parent::getBillingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCity($billing_city)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCity', [$billing_city]);

        return parent::setBillingCity($billing_city);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingState()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingState', []);

        return parent::getBillingState();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingState($billing_state)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingState', [$billing_state]);

        return parent::setBillingState($billing_state);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingZip()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingZip', []);

        return parent::getBillingZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingZip($billing_zip)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingZip', [$billing_zip]);

        return parent::setBillingZip($billing_zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCountry()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCountry', []);

        return parent::getBillingCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCountry($billing_country)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCountry', [$billing_country]);

        return parent::setBillingCountry($billing_country);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingPhone()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingPhone', []);

        return parent::getBillingPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingPhone($billing_phone)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingPhone', [$billing_phone]);

        return parent::setBillingPhone($billing_phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingFax()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingFax', []);

        return parent::getBillingFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingFax($billing_fax)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingFax', [$billing_fax]);

        return parent::setBillingFax($billing_fax);
    }

    /**
     * {@inheritDoc}
     */
    public function populateBillingAddress()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populateBillingAddress', []);

        return parent::populateBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingFirstName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingFirstName', []);

        return parent::getBillingFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingLastName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingLastName', []);

        return parent::getBillingLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferral()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferral', []);

        return parent::getReferral();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferral($referral)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferral', [$referral]);

        return parent::setReferral($referral);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefDescription()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefDescription', []);

        return parent::getRefDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefDescription($ref_description)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefDescription', [$ref_description]);

        return parent::setRefDescription($ref_description);
    }

    /**
     * {@inheritDoc}
     */
    public function addProgramType(\Fisdap\Entity\ProgramTypeLegacy $programTypeLegacy)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProgramType', [$programTypeLegacy]);

        return parent::addProgramType($programTypeLegacy);
    }

    /**
     * {@inheritDoc}
     */
    public function addProgramTypes(array $programTypes)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProgramTypes', [$programTypes]);

        return parent::addProgramTypes($programTypes);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramTypes()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramTypes', []);

        return parent::getProgramTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramTypeIds($ids)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramTypeIds', [$ids]);

        return parent::setProgramTypeIds($ids);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramTypeIds()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramTypeIds', []);

        return parent::getProgramTypeIds();
    }

    /**
     * {@inheritDoc}
     */
    public function isTrainingProgram()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTrainingProgram', []);

        return parent::isTrainingProgram();
    }

    /**
     * {@inheritDoc}
     */
    public function isHospital()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHospital', []);

        return parent::isHospital();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccredited()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccredited', []);

        return parent::getAccredited();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccredited($accredited)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccredited', [$accredited]);

        return parent::setAccredited($accredited);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoaemspProgramId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoaemspProgramId', []);

        return parent::getCoaemspProgramId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoaemspProgramId($coaemsp_program_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoaemspProgramId', [$coaemsp_program_id]);

        return parent::setCoaemspProgramId($coaemsp_program_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearAccredited()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearAccredited', []);

        return parent::getYearAccredited();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearAccredited($year_accredited)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearAccredited', [$year_accredited]);

        return parent::setYearAccredited($year_accredited);
    }

    /**
     * {@inheritDoc}
     */
    public function set_can_students_create_field($value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_can_students_create_field', [$value]);

        return parent::set_can_students_create_field($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_can_students_create_field()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_can_students_create_field', []);

        return parent::get_can_students_create_field();
    }

    /**
     * {@inheritDoc}
     */
    public function set_can_students_create_clinical($value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_can_students_create_clinical', [$value]);

        return parent::set_can_students_create_clinical($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_can_students_create_clinical()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_can_students_create_clinical', []);

        return parent::get_can_students_create_clinical();
    }

    /**
     * {@inheritDoc}
     */
    public function set_can_students_create_lab($value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_can_students_create_lab', [$value]);

        return parent::set_can_students_create_lab($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_can_students_create_lab()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_can_students_create_lab', []);

        return parent::get_can_students_create_lab();
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentViewFullCalendar()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentViewFullCalendar', []);

        return parent::getStudentViewFullCalendar();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudentViewFullCalendar($student_view_full_calendar)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudentViewFullCalendar', [$student_view_full_calendar]);

        return parent::setStudentViewFullCalendar($student_view_full_calendar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanStudentsPickField()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanStudentsPickField', []);

        return parent::getCanStudentsPickField();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanStudentsPickField($can_students_pick_field)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanStudentsPickField', [$can_students_pick_field]);

        return parent::setCanStudentsPickField($can_students_pick_field);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanStudentsPickClinical()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanStudentsPickClinical', []);

        return parent::getCanStudentsPickClinical();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanStudentsPickClinical($can_students_pick_clinical)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanStudentsPickClinical', [$can_students_pick_clinical]);

        return parent::setCanStudentsPickClinical($can_students_pick_clinical);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanStudentsPickLab()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanStudentsPickLab', []);

        return parent::getCanStudentsPickLab();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanStudentsPickLab($can_students_pick_lab)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanStudentsPickLab', [$can_students_pick_lab]);

        return parent::setCanStudentsPickLab($can_students_pick_lab);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowAbsentWithPermission()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowAbsentWithPermission', []);

        return parent::getAllowAbsentWithPermission();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowAbsentWithPermission($allow_absent_with_permission)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowAbsentWithPermission', [$allow_absent_with_permission]);

        return parent::setAllowAbsentWithPermission($allow_absent_with_permission);
    }

    /**
     * {@inheritDoc}
     */
    public function isIncludeNarrative()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIncludeNarrative', []);

        return parent::isIncludeNarrative();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncludeNarrative($include_narrative)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncludeNarrative', [$include_narrative]);

        return parent::setIncludeNarrative($include_narrative);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendLateShiftEmails()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendLateShiftEmails', []);

        return parent::getSendLateShiftEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendLateShiftEmails($send_late_shift_emails)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendLateShiftEmails', [$send_late_shift_emails]);

        return parent::setSendLateShiftEmails($send_late_shift_emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendCriticalThinkingEmails()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendCriticalThinkingEmails', []);

        return parent::getSendCriticalThinkingEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendCriticalThinkingEmails($send_critical_thinking_emails)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendCriticalThinkingEmails', [$send_critical_thinking_emails]);

        return parent::setSendCriticalThinkingEmails($send_critical_thinking_emails);
    }

    /**
     * {@inheritDoc}
     */
    public function getLateFieldDeadline()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLateFieldDeadline', []);

        return parent::getLateFieldDeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function setLateFieldDeadline($late_field_deadline)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLateFieldDeadline', [$late_field_deadline]);

        return parent::setLateFieldDeadline($late_field_deadline);
    }

    /**
     * {@inheritDoc}
     */
    public function getLateClinicalDeadline()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLateClinicalDeadline', []);

        return parent::getLateClinicalDeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function setLateClinicalDeadline($late_clinical_deadline)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLateClinicalDeadline', [$late_clinical_deadline]);

        return parent::setLateClinicalDeadline($late_clinical_deadline);
    }

    /**
     * {@inheritDoc}
     */
    public function getLateLabDeadline()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLateLabDeadline', []);

        return parent::getLateLabDeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function setLateLabDeadline($late_lab_deadline)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLateLabDeadline', [$late_lab_deadline]);

        return parent::setLateLabDeadline($late_lab_deadline);
    }

    /**
     * {@inheritDoc}
     */
    public function generateCustomerName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateCustomerName', []);

        return parent::generateCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', []);

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiresPo()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequiresPo', []);

        return parent::getRequiresPo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequiresPo($requires_po)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequiresPo', [$requires_po]);

        return parent::setRequiresPo($requires_po);
    }

    /**
     * {@inheritDoc}
     */
    public function generateProductCodeId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateProductCodeId', []);

        return parent::generateProductCodeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCodeId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCodeId', []);

        return parent::getProductCodeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderPermission()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderPermission', []);

        return parent::getOrderPermission();
    }

    /**
     * {@inheritDoc}
     */
    public function set_order_permission($value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_order_permission', [$value]);

        return parent::set_order_permission($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderPermission(\Fisdap\Entity\OrderPermission $orderPermission)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderPermission', [$orderPermission]);

        return parent::setOrderPermission($orderPermission);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveReports()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveReports', []);

        return parent::getActiveReports();
    }

    /**
     * {@inheritDoc}
     */
    public function isActiveReport($report_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActiveReport', [$report_id]);

        return parent::isActiveReport($report_id);
    }

    /**
     * {@inheritDoc}
     */
    public function isAssociatedReport($report_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAssociatedReport', [$report_id]);

        return parent::isAssociatedReport($report_id);
    }

    /**
     * {@inheritDoc}
     */
    public function addReport($report_id, $active = 1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReport', [$report_id, $active]);

        return parent::addReport($report_id, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function toggleReport($report_id, $active)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toggleReport', [$report_id, $active]);

        return parent::toggleReport($report_id, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function createDemoSites()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDemoSites', []);

        return parent::createDemoSites();
    }

    /**
     * {@inheritDoc}
     */
    public function usesSharing()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'usesSharing', []);

        return parent::usesSharing();
    }

    /**
     * {@inheritDoc}
     */
    public function isActiveSite($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActiveSite', [$site_id]);

        return parent::isActiveSite($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function sharesSite($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sharesSite', [$site_id]);

        return parent::sharesSite($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetworkPrograms($site)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetworkPrograms', [$site]);

        return parent::getNetworkPrograms($site);
    }

    /**
     * {@inheritDoc}
     */
    public function pendingApproval($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pendingApproval', [$site_id]);

        return parent::pendingApproval($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function isAdmin($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAdmin', [$site_id]);

        return parent::isAdmin($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function seesSharedStudents($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'seesSharedStudents', [$site_id]);

        return parent::seesSharedStudents($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function addSite(\Fisdap\Entity\SiteLegacy $site, $active = 1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSite', [$site, $active]);

        return parent::addSite($site, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function hasSite(\Fisdap\Entity\SiteLegacy $site)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasSite', [$site]);

        return parent::hasSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSite(\Fisdap\Entity\SiteLegacy $site)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSite', [$site]);

        return parent::removeSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function toggleSite(\Fisdap\Entity\SiteLegacy $site, $active)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toggleSite', [$site, $active]);

        return parent::toggleSite($site, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedStatus($site_id)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedStatus', [$site_id]);

        return parent::getSharedStatus($site_id);
    }

    /**
     * {@inheritDoc}
     */
    public function hasBase(\Fisdap\Entity\BaseLegacy $base)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasBase', [$base]);

        return parent::hasBase($base);
    }

    /**
     * {@inheritDoc}
     */
    public function addBase(\Fisdap\Entity\BaseLegacy $base, $active = 1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBase', [$base, $active]);

        return parent::addBase($base, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBase(\Fisdap\Entity\BaseLegacy $base)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBase', [$base]);

        return parent::removeBase($base);
    }

    /**
     * {@inheritDoc}
     */
    public function toggleBase(\Fisdap\Entity\BaseLegacy $base, $active)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toggleBase', [$base, $active]);

        return parent::toggleBase($base, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function addPreceptor(\Fisdap\Entity\PreceptorLegacy $preceptor, $active = 1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreceptor', [$preceptor, $active]);

        return parent::addPreceptor($preceptor, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function togglePreceptor(\Fisdap\Entity\PreceptorLegacy $preceptor, $active)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'togglePreceptor', [$preceptor, $active]);

        return parent::togglePreceptor($preceptor, $active);
    }

    /**
     * {@inheritDoc}
     */
    public function hasSkillsPractice()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasSkillsPractice', []);

        return parent::hasSkillsPractice();
    }

    /**
     * {@inheritDoc}
     */
    public function createDefaultNarrativeSection()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDefaultNarrativeSection', []);

        return parent::createDefaultNarrativeSection();
    }

    /**
     * {@inheritDoc}
     */
    public function createDefaultPracticeDefinitions()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDefaultPracticeDefinitions', []);

        return parent::createDefaultPracticeDefinitions();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirwayProcedures(array $airway_procedures)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirwayProcedures', [$airway_procedures]);

        return parent::setAirwayProcedures($airway_procedures);
    }

    /**
     * {@inheritDoc}
     */
    public function setCardiacProcedures(array $cardiac_procedures)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardiacProcedures', [$cardiac_procedures]);

        return parent::setCardiacProcedures($cardiac_procedures);
    }

    /**
     * {@inheritDoc}
     */
    public function setIvProcedures(array $iv_procedures)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIvProcedures', [$iv_procedures]);

        return parent::setIvProcedures($iv_procedures);
    }

    /**
     * {@inheritDoc}
     */
    public function setOtherProcedures(array $other_procedures)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtherProcedures', [$other_procedures]);

        return parent::setOtherProcedures($other_procedures);
    }

    /**
     * {@inheritDoc}
     */
    public function setMedTypes(array $med_types)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedTypes', [$med_types]);

        return parent::setMedTypes($med_types);
    }

    /**
     * {@inheritDoc}
     */
    public function setLabAssessments(array $lab_assessments)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabAssessments', [$lab_assessments]);

        return parent::setLabAssessments($lab_assessments);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirwayProcedures()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirwayProcedures', []);

        return parent::getAirwayProcedures();
    }

    /**
     * {@inheritDoc}
     */
    public function getCardiacProcedures()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardiacProcedures', []);

        return parent::getCardiacProcedures();
    }

    /**
     * {@inheritDoc}
     */
    public function getIvProcedures()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIvProcedures', []);

        return parent::getIvProcedures();
    }

    /**
     * {@inheritDoc}
     */
    public function getOtherProcedures()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherProcedures', []);

        return parent::getOtherProcedures();
    }

    /**
     * {@inheritDoc}
     */
    public function getMedTypes()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedTypes', []);

        return parent::getMedTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabAssessments()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabAssessments', []);

        return parent::getLabAssessments();
    }

    /**
     * {@inheritDoc}
     */
    public function sendNewRequirementNotification($requirementId)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sendNewRequirementNotification', [$requirementId]);

        return parent::sendNewRequirementNotification($requirementId);
    }

    /**
     * {@inheritDoc}
     */
    public function get_use_scheduler()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_use_scheduler', []);

        return parent::get_use_scheduler();
    }

    /**
     * {@inheritDoc}
     */
    public function getSchedulerUrl()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchedulerUrl', []);

        return parent::getSchedulerUrl();
    }
}
