<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \User\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'invalidFields', 'id', 'shift', 'run', 'student', 'signoff', 'verification', 'locked', 'team_lead', 'team_size', 'response_mode', 'age', 'months', 'legacy_assessment_id', 'legacy_run_id', 'gender', 'ethnicity', 'primary_impression', 'secondary_impression', 'complaints', 'witness', 'pulse_return', 'mechanisms', 'cause', 'intent', 'interview', 'exam', 'airway_success', 'airway_management', 'patient_criticality', 'patient_disposition', 'transport_mode', 'msa_alertness', 'msa_orientations', 'msa_responses', 'meds', 'other_interventions', 'cardiac_interventions', 'airways', 'ivs', 'narrative', 'vitals', 'subject', '' . "\0" . 'User\\Entity\\Patient' . "\0" . 'missingFields'];
        }

        return ['__isInitialized__', 'invalidFields', 'id', 'shift', 'run', 'student', 'signoff', 'verification', 'locked', 'team_lead', 'team_size', 'response_mode', 'age', 'months', 'legacy_assessment_id', 'legacy_run_id', 'gender', 'ethnicity', 'primary_impression', 'secondary_impression', 'complaints', 'witness', 'pulse_return', 'mechanisms', 'cause', 'intent', 'interview', 'exam', 'airway_success', 'airway_management', 'patient_criticality', 'patient_disposition', 'transport_mode', 'msa_alertness', 'msa_orientations', 'msa_responses', 'meds', 'other_interventions', 'cardiac_interventions', 'airways', 'ivs', 'narrative', 'vitals', 'subject', '' . "\0" . 'User\\Entity\\Patient' . "\0" . 'missingFields'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function init()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', []);

        return parent::init();
    }

    /**
     * {@inheritDoc}
     */
    public function get_subject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_subject', []);

        return parent::get_subject();
    }

    /**
     * {@inheritDoc}
     */
    public function set_subject($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_subject', [$value]);

        return parent::set_subject($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_verification(\User\Entity\Verification $ver = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_verification', [$ver]);

        return parent::set_verification($ver);
    }

    /**
     * {@inheritDoc}
     */
    public function set_ethnicity($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_ethnicity', [$value]);

        return parent::set_ethnicity($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_primary_impression($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_primary_impression', [$value]);

        return parent::set_primary_impression($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_secondary_impression($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_secondary_impression', [$value]);

        return parent::set_secondary_impression($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_gender($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_gender', [$value]);

        return parent::set_gender($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_preceptor($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_preceptor', [$value]);

        return parent::set_preceptor($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_response_mode($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_response_mode', [$value]);

        return parent::set_response_mode($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_msa_alertness($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_msa_alertness', [$value]);

        return parent::set_msa_alertness($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_cause($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_cause', [$value]);

        return parent::set_cause($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_intent($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_intent', [$value]);

        return parent::set_intent($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_patient_criticality($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_patient_criticality', [$value]);

        return parent::set_patient_criticality($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_patient_disposition($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_patient_disposition', [$value]);

        return parent::set_patient_disposition($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_transport_mode($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_transport_mode', [$value]);

        return parent::set_transport_mode($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_witness($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_witness', [$value]);

        return parent::set_witness($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_pulse_return($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_pulse_return', [$value]);

        return parent::set_pulse_return($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_age($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_age', [$value]);

        return parent::set_age($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_months($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_months', [$value]);

        return parent::set_months($value);
    }

    /**
     * {@inheritDoc}
     */
    public function set_narrative($narrative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_narrative', [$narrative]);

        return parent::set_narrative($narrative);
    }

    /**
     * {@inheritDoc}
     */
    public function set_signoff($signoff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_signoff', [$signoff]);

        return parent::set_signoff($signoff);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($patientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$patientId]);

        return parent::setId($patientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRun', []);

        return parent::getRun();
    }

    /**
     * {@inheritDoc}
     */
    public function setShift(\User\Entity\ShiftLegacy $shift)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShift', [$shift]);

        return parent::setShift($shift);
    }

    /**
     * {@inheritDoc}
     */
    public function getShift()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShift', []);

        return parent::getShift();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent(\User\Entity\StudentLegacy $student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', [$student]);

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', []);

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamLead($teamLead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamLead', [$teamLead]);

        return parent::setTeamLead($teamLead);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamLead', []);

        return parent::getTeamLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamSize($teamSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamSize', [$teamSize]);

        return parent::setTeamSize($teamSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamSize', []);

        return parent::getTeamSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($locked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', [$locked]);

        return parent::setLocked($locked);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocked', []);

        return parent::getLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(\User\Entity\Subject $subject = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setEthnicity(\User\Entity\Ethnicity $ethnicity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEthnicity', [$ethnicity]);

        return parent::setEthnicity($ethnicity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEthnicity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEthnicity', []);

        return parent::getEthnicity();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerification(\User\Entity\Verification $ver = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerification', [$ver]);

        return parent::setVerification($ver);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerificationArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerificationArray', []);

        return parent::getVerificationArray();
    }

    /**
     * {@inheritDoc}
     */
    public function unsetVerification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unsetVerification', []);

        return parent::unsetVerification();
    }

    /**
     * {@inheritDoc}
     */
    public function getVerification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerification', []);

        return parent::getVerification();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryImpression(\User\Entity\Impression $impression)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryImpression', [$impression]);

        return parent::setPrimaryImpression($impression);
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondaryImpression(\User\Entity\Impression $impression = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondaryImpression', [$impression]);

        return parent::setSecondaryImpression($impression);
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(\User\Entity\Gender $gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreceptor(\User\Entity\PreceptorLegacy $preceptorLegacy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreceptor', [$preceptorLegacy]);

        return parent::setPreceptor($preceptorLegacy);
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseMode(\User\Entity\ResponseMode $responseMode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseMode', [$responseMode]);

        return parent::setResponseMode($responseMode);
    }

    /**
     * {@inheritDoc}
     */
    public function setMsaAlertness(\User\Entity\MentalAlertness $mentalAlertness = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsaAlertness', [$mentalAlertness]);

        return parent::setMsaAlertness($mentalAlertness);
    }

    /**
     * {@inheritDoc}
     */
    public function setMsaOrientations($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsaOrientations', [$value]);

        return parent::setMsaOrientations($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCause(\User\Entity\Cause $cause = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCause', [$cause]);

        return parent::setCause($cause);
    }

    /**
     * {@inheritDoc}
     */
    public function setIntent(\User\Entity\Intent $intent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntent', [$intent]);

        return parent::setIntent($intent);
    }

    /**
     * {@inheritDoc}
     */
    public function setInterview($interview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterview', [$interview]);

        return parent::setInterview($interview);
    }

    /**
     * {@inheritDoc}
     */
    public function setExam($exam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExam', [$exam]);

        return parent::setExam($exam);
    }

    /**
     * {@inheritDoc}
     */
    public function setAirwaySuccess($airwaySuccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirwaySuccess', [$airwaySuccess]);

        return parent::setAirwaySuccess($airwaySuccess);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientCriticality(\User\Entity\PatientCriticality $patientCriticality = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientCriticality', [$patientCriticality]);

        return parent::setPatientCriticality($patientCriticality);
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientDisposition(\User\Entity\PatientDisposition $patientDisposition = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientDisposition', [$patientDisposition]);

        return parent::setPatientDisposition($patientDisposition);
    }

    /**
     * {@inheritDoc}
     */
    public function setTransportMode(\User\Entity\ResponseMode $responseMode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransportMode', [$responseMode]);

        return parent::setTransportMode($responseMode);
    }

    /**
     * {@inheritDoc}
     */
    public function setWitness(\User\Entity\Witness $witness = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWitness', [$witness]);

        return parent::setWitness($witness);
    }

    /**
     * {@inheritDoc}
     */
    public function setPulseReturn(\User\Entity\PulseReturn $pulseReturn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPulseReturn', [$pulseReturn]);

        return parent::setPulseReturn($pulseReturn);
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonths($month)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonths', [$month]);

        return parent::setMonths($month);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonths', []);

        return parent::getMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setNarrative(\User\Entity\Narrative $narrative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNarrative', [$narrative]);

        return parent::setNarrative($narrative);
    }

    /**
     * {@inheritDoc}
     */
    public function getNarrative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNarrative', []);

        return parent::getNarrative();
    }

    /**
     * {@inheritDoc}
     */
    public function getVitals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVitals', []);

        return parent::getVitals();
    }

    /**
     * {@inheritDoc}
     */
    public function setVitals($vitals)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVitals', [$vitals]);

        return parent::setVitals($vitals);
    }

    /**
     * {@inheritDoc}
     */
    public function getIvs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIvs', []);

        return parent::getIvs();
    }

    /**
     * {@inheritDoc}
     */
    public function setIvs($ivs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIvs', [$ivs]);

        return parent::setIvs($ivs);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirways()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirways', []);

        return parent::getAirways();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirways($airways)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirways', [$airways]);

        return parent::setAirways($airways);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardiacInterventions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardiacInterventions', []);

        return parent::getCardiacInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardiacInterventions($cardiac_interventions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardiacInterventions', [$cardiac_interventions]);

        return parent::setCardiacInterventions($cardiac_interventions);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplaints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplaints', []);

        return parent::getComplaints();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplaints($complaints)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplaints', [$complaints]);

        return parent::setComplaints($complaints);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirwayManagement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirwayManagement', []);

        return parent::getAirwayManagement();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirwayManagement($airway_management)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirwayManagement', [$airway_management]);

        return parent::setAirwayManagement($airway_management);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeds', []);

        return parent::getMeds();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeds($meds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeds', [$meds]);

        return parent::setMeds($meds);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtherInterventions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherInterventions', []);

        return parent::getOtherInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function setOtherInterventions($other_interventions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtherInterventions', [$other_interventions]);

        return parent::setOtherInterventions($other_interventions);
    }

    /**
     * {@inheritDoc}
     */
    public function setSignoff(\User\Entity\PreceptorSignoff $signoff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignoff', [$signoff]);

        return parent::setSignoff($signoff);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignoffArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignoffArray', []);

        return parent::getSignoffArray();
    }

    /**
     * {@inheritDoc}
     */
    public function addMed(\User\Entity\Med $med)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMed', [$med]);

        return parent::addMed($med);
    }

    /**
     * {@inheritDoc}
     */
    public function addOtherIntervention(\User\Entity\OtherIntervention $other)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOtherIntervention', [$other]);

        return parent::addOtherIntervention($other);
    }

    /**
     * {@inheritDoc}
     */
    public function addCardiacIntervention(\User\Entity\CardiacIntervention $cardiac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCardiacIntervention', [$cardiac]);

        return parent::addCardiacIntervention($cardiac);
    }

    /**
     * {@inheritDoc}
     */
    public function addAirway(\User\Entity\Airway $air)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAirway', [$air]);

        return parent::addAirway($air);
    }

    /**
     * {@inheritDoc}
     */
    public function addIv(\User\Entity\Iv $iv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIv', [$iv]);

        return parent::addIv($iv);
    }

    /**
     * {@inheritDoc}
     */
    public function addVital(\User\Entity\Vital $vital)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVital', [$vital]);

        return parent::addVital($vital);
    }

    /**
     * {@inheritDoc}
     */
    public function setComplaintIds($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplaintIds', [$value]);

        return parent::setComplaintIds($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplaintIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplaintIds', []);

        return parent::getComplaintIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getComplaintNames($sortComplaints = true, $delimiter = ', ')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplaintNames', [$sortComplaints, $delimiter]);

        return parent::getComplaintNames($sortComplaints, $delimiter);
    }

    /**
     * {@inheritDoc}
     */
    public function set_mechanisms($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_mechanisms', [$value]);

        return parent::set_mechanisms($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_mechanisms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_mechanisms', []);

        return parent::get_mechanisms();
    }

    /**
     * {@inheritDoc}
     */
    public function getMechanismIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMechanismIds', []);

        return parent::getMechanismIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getMechanismNames($sort = true, $delimiter = ', ')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMechanismNames', [$sort, $delimiter]);

        return parent::getMechanismNames($sort, $delimiter);
    }

    /**
     * {@inheritDoc}
     */
    public function set_msa_orientations($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_msa_orientations', [$value]);

        return parent::set_msa_orientations($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_msa_orientations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_msa_orientations', []);

        return parent::get_msa_orientations();
    }

    /**
     * {@inheritDoc}
     */
    public function set_msa_responses($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_msa_responses', [$value]);

        return parent::set_msa_responses($value);
    }

    /**
     * {@inheritDoc}
     */
    public function get_msa_responses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_msa_responses', []);

        return parent::get_msa_responses();
    }

    /**
     * {@inheritDoc}
     */
    public function getSummaryLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummaryLine', []);

        return parent::getSummaryLine();
    }

    /**
     * {@inheritDoc}
     */
    public function generateSummarySeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateSummarySeed', []);

        return parent::generateSummarySeed();
    }

    /**
     * {@inheritDoc}
     */
    public function isValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', []);

        return parent::isValid();
    }

    /**
     * {@inheritDoc}
     */
    public function isALSPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isALSPatient', []);

        return parent::isALSPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function isUnconscious()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUnconscious', []);

        return parent::isUnconscious();
    }

    /**
     * {@inheritDoc}
     */
    public function isALSPatientTest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isALSPatientTest', []);

        return parent::isALSPatientTest();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvalidFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvalidFields', []);

        return parent::getInvalidFields();
    }

    /**
     * {@inheritDoc}
     */
    public function getNarrativeArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNarrativeArray', []);

        return parent::getNarrativeArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getHookIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHookIds', []);

        return parent::getHookIds();
    }

    /**
     * {@inheritDoc}
     */
    public function canBeLocked($shiftType = 'field')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canBeLocked', [$shiftType]);

        return parent::canBeLocked($shiftType);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissingFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissingFields', []);

        return parent::getMissingFields();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
