<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Run extends \User\Entity\Run implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'shift', 'student', 'signoff', 'verification', 'locked', 'soft_deleted', 'patients', 'invalidPatients'];
        }

        return ['__isInitialized__', 'id', 'shift', 'student', 'signoff', 'verification', 'locked', 'soft_deleted', 'patients', 'invalidPatients'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (! $this->__isInitialized__) {
            $this->__initializer__ = function (Run $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function init()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', []);

        return parent::init();
    }

    /**
     * {@inheritDoc}
     */
    public function set_signoff($signoff)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_signoff', [$signoff]);

        return parent::set_signoff($signoff);
    }

    /**
     * {@inheritDoc}
     */
    public function set_verification(\User\Entity\Verification $ver = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_verification', [$ver]);

        return parent::set_verification($ver);
    }

    /**
     * {@inheritDoc}
     */
    public function addPatient(\User\Entity\Patient $patient)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPatient', [$patient]);

        return parent::addPatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function removePatient(\User\Entity\Patient $patient)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePatient', [$patient]);

        return parent::removePatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function isEditable($user = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEditable', [$user]);

        return parent::isEditable($user);
    }

    /**
     * {@inheritDoc}
     */
    public function isValid()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', []);

        return parent::isValid();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvalidPatients()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvalidPatients', []);

        return parent::getInvalidPatients();
    }
}
