    <?= $this->pageTitleHelper() ?>

<div class="grid_12 island">

	<div class="grid_6">

		<h4 class="header">
			<a href="/reports/index/legacy">Evals & Skill Sheets</a>
		</h4>

		<p>
            View all completed evaluations and skill sheets for your program, including Eureka Graphs.
		</p>

		<br />

		<p><a href="/reports/index/legacy">Go to Evals & Skill Sheets.</a></p>

	</div>

	<div class="grid_6">

		<h4 class="header">
			<a href="/reports">Reports</a>
		</h4>

		<p>
            The reporting system features advanced customization options, a Report History for conveniently repeating reports, sortable
            results, links from skill and patient data back to the shifts in Skills Tracker, and more.
		</p>

		<br />

		<p><a href="/reports">Go to Reports.</a></p>

	</div>

</div>