Ages:
<ul>
    <li>Newborn starts at 0</li>
    <li>Infant starts at <?= $this->goalset->infant_start_age ?> (months)</li>
    <li>Toddler starts at <?= $this->goalset->toddler_start_age ?> (years)</li>
    <li>Preschooler starts at <?= $this->goalset->preschooler_start_age ?> (years)</li>
    <li>School age starts at <?= $this->goalset->school_age_start_age ?> (years)</li>
    <li>Adolescent starts at <?= $this->goalset->adolescent_start_age ?> (years)</li>
    <li>Adult starts at <?= $this->goalset->adult_start_age ?> (years)</li>
    <li>Geriatric starts at <?= $this->goalset->geriatric_start_age ?> (years)</li>
</ul>
