<h1><?= $this->element->event->region ?> -
<?= $this->element->event->start_date->format("F d-") ?>
<?= $this->element->event->end_date->format("F d, Y") ?>
</h1>
<h1><?= $this->element->event->origin ?> to
<?= $this->element->event->destination ?></h1>
<div class="grid_6">
<h5 class="section-header">
<?= $this->element->event->notes ?></h5>
<br>
<h4>Contact Info</h4>
<hr> 
<?= $this->element->firstName; ?>
<div class="clear"></div>
<?= $this->element->lastName; ?>
<div class="clear"></div>
<?= $this->element->homePhone; ?>
<div class="clear"></div>
<?= $this->element->workPhone; ?>
<div class="clear"></div>
<?= $this->element->cellPhone; ?>
<div class="clear"></div>
<h4>Address</h4>
<hr>
<?= $this->element->address1; ?>
<div class="clear"></div>
<?= $this->element->address2; ?>
<div class="clear"></div>
<?= $this->element->city; ?>
<div class="clear"></div>
<?= $this->element->state; ?>
<div class="clear"></div>
<?= $this->element->zip; ?>
<div class="clear"></div>
<?= $this->element->email; ?>
<div class="clear"></div>
<h4>Emergency Contact</h4>
<hr>
<?= $this->element->emName; ?>
<div class="clear"></div>
<?= $this->element->emRel; ?>
<div class="clear"></div>
<?= $this->element->emPhone; ?>
<div class="clear"></div>
<h4>Role</h4>
<hr>	
<?= $this->element->role; ?>
<div class="clear"></div>
<br>
<?php if(trim($this->element->event->route_information) != ""){ ?>
	<h4>Route Information</h4>
	<hr>
	<?= $this->element->event->route_information; ?>
	<div class="clear"></div>
	<br />
<?php } ?>
<h4>Participating Days</h4>
<hr>
<?= $this->element->days; ?>
<br />
<?= $this->element->guests; ?>
<br>
<?php if(!is_null($this->element->event->housing)){
echo '<h4>Housing</h4>';
echo '<hr>';
echo '<p>';
echo nl2br($this->element->event->housing); 
echo '</p>';
echo '<br>';
}?>

<?php if(!is_null($this->element->event->transportation)){
echo '<h4>Transportation and Parking</h4>';
echo '<hr>';
echo '<p>';
echo nl2br($this->element->event->transportation);
echo '</p>';
echo '<br>';
}?>



<?php if((!is_null($this->element->event->jersey)) || (!is_null($this->element->event->tshirt))){
echo '<h4>Merchandise</h4>';
echo '<hr>';
}
?>

<?php if(!is_null($this->element->event->jersey)){
echo '<h5>Jersey</h5>';
echo '<div id="JerseySize_div">';
echo '<span class="ridingjersey">';
echo nl2br($this->element->event->jersey);
echo '<br>';
echo '</span>';
echo '</div>';
echo "<div id='sizingModal'>"; 
echo "<img src='/images/sizingchart.jpg'>";
echo '</div>';
echo $this->element->jerseysize;
}
?>


<?php if(!is_null($this->element->event->tshirt)){
echo '<div class="clear"></div>';
echo '<br>';
echo '<h5>T-Shirt</h5>';
echo '<p>';
echo nl2br($this->element->event->tshirt);
echo '</p>';
echo $this->element->tshirtsize;
}
?>
<div class="clear"></div>
<br>
<h4>Special Needs</h4>
<hr>
<p>This is a privately run event open to the public. This is a physical event. We encourage anyone
interested in participating to do so and we will try to accommodate special needs to the best of our
ability. If you have special needs that you would like to share with us, to assist us in making your
experience a pleasant one, please indicate.</p>
<p>Please note significant food allergies or vegetarian requests.  
Many of our meals and snacks are provided by outside agencies so we do not have control over what they choose to provide however we will attempt to provide appropriate options. </p>
<?= $this->element->special; ?>
<div class="clear"></div>
<br>
<!--
<h4>Why are you participating?</h4>
<hr>
<?= $this->element->why; ?>	
<div class="clear"></div>
<br>
<h4>Comments and Suggestions</h4>
<hr>
<?= $this->element->comments; ?>
<div class="clear"></div>
<br>
-->
<h4>Liability Release *</h4>
<hr>
<?= $this->element->liability; ?>
<?= $this->element->eventId; ?>
<div class="clear"></div>
</div>
<div class="grid_12">
<!--
<p>In addition, please print off and bring a signed copy of the following with you.
It will be collected at registration.</p>
-->
<br><br>
<div id="bikeride-liability">
	<a href="#" class="pdfLink">Print Release of Liability</a>
</div>
<br><br><br>

<div id="releaseForm">
	
<p><?= nl2br($this->element->event->liability); ?></p>
    
</div>

<hr>
<br>
<?= $this->element->submit; ?>
</div>

	
	
	
	