<h4>Event Information:</h4>
<hr>
<?= $this->element->region; ?>    
<?= $this->element->origin; ?>
<?= $this->element->destination; ?>
<?= $this->element->passcode; ?>
<?= $this->element->email_list; ?>
<?= $this->element->route_info; ?>
<?= $this->element->roles; ?>
<?= $this->element->start; ?>
<?= $this->element->end; ?>
<?= $this->element->housingtoggle; ?>
<?= $this->element->housing; ?>
<?= $this->element->transporttoggle; ?>
<?= $this->element->transportation; ?>
<?= $this->element->jerseytoggle; ?>
<?= $this->element->jerseytext; ?>
<?= $this->element->tshirttoggle; ?>
<?= $this->element->tshirttext; ?>
<?= $this->element->liability; ?>
<?= $this->element->notes; ?>
<?= $this->element->eventId; ?>
<?= $this->element->submit; ?>