<h3 class="page-title">Thank you for your interest in attending a Fisdap workshop. If your workshop is not
listed, or if you have any questions while completing this form, please call us at 651-690-9241.</h3>
<br>

<div class="grid_8">
	
	<h4>Workshop Dates & Locations</h4>
	<hr> 
	<?= $this->element->locations; ?>
	<div class="clear"></div>
	<br>
		
	<h4>Contact Information</h4>
	<hr>
	<?= $this->element->firstName; ?>
	<div class="clear"></div>
	<?= $this->element->lastName; ?>
	<div class="clear"></div>
	<?= $this->element->userName; ?>
	<div class="clear"></div>
	<?= $this->element->phone; ?>
	<div class="clear"></div>
	<?= $this->element->email; ?>
	<div class="clear"></div>
	<?= $this->element->organization; ?>
	<div class="clear"></div>
	<br>
		
	<h4>Certifications</h4>
	<hr>
	<?= $this->element->certLevels; ?>
	<div class="clear"></div>
	<?= $this->element->certNumber; ?>
	<div class="clear"></div>
	<?= $this->element->certTaught; ?>
	<div class="clear"></div>	
	<br>
		
	<h4>Mailing Address</h4>
	<hr>
	<?= $this->element->address1; ?>
	<div class="clear"></div>		
	<?= $this->element->address2; ?>
	<div class="clear"></div>
	<?= $this->element->city; ?>
	<div class="clear"></div>
	<?= $this->element->state; ?>
	<div class="clear"></div>
	<?= $this->element->zip; ?>
	<div class="clear"></div>
	<br>
		
	<hr>
	<?= $this->element->submit; ?>	
	
</div>