<div class="grid_6">
    
    <h4>Edit workshop information below:</h4>
    <hr> 
    <?= $this->element->date; ?>
    <div class="clear"></div>
    <?= $this->element->deadline; ?>
    <div class="clear"></div>
    <?= $this->element->location; ?>
    <div class="clear"></div>
    <?= $this->element->duration; ?>
    <div class="clear"></div>
    <?= $this->element->emailSubject; ?>
    <div class="clear"></div>
    <?= $this->element->emailBody; ?>
    <div class="clear"></div>
    <?= $this->element->cost; ?>
    <div class="clear"></div>
    <?= $this->element->workshopId; ?>
    <div class="clear"></div>    
    <br>
    <hr>    
    <?= $this->element->submit; ?>
    <div class="clear"></div>       
    <br>    
    
</div>