<?= $this->pageTitleHelper() ?>
<div class="grid_12 island">
    <h2 class="section-header">Questions</h3>
    <div class="grid_11 prefix_1">
       <ul>
            <li><a href="#q1">How is an exam validated?</a>
            <li><a href="#q2">What is "reliability"?</a>
            <li><a href="#q3">How do you determine an exam's predictability?</a>
            <li><a href="#q4">Are Fisdap exams computer adaptive like the National Registry Cognitive Exam?</a>
            <li><a href="#q5">How do students get their results?</a>
            <li><a href="#q6">Does Fisdap provide feedback on the students' performances?</a>
            <li><a href="#q7">How do I get my students' National Registry Cognitive Exam results?</a>
        </ul> 
    </div>
    
        
    <h2 class="section-header">Answers</h3>
    <div class="grid_11 prefix_1">
        <div class='question'>
            <a name="q1"></a><h4 class="section-header no-border">Q. How is an exam validated?</h4>
            <p class='answer'>
                All of the content in the exam is reviewed by Subject 
                Matter Experts (SMEs) who ensure that it is correct, 
                current, comprehensive, and challenging.  Each exam is 
                blueprinted to ensure that the content addresses the 
                chief objectives of the curriculum.
            </p>
        </div>
        
        <div class="question">
            <a name="q2"></a><h4 class="section-header no-border">Q. What is "reliability"?</h4>
            <p class='answer'>
                After an exam has been validated, it is pilot-tested 
                (i.e. administered to a study group) and analyzed for 
                reliability.  Using 
                <a href="http://en.wikipedia.org/wiki/Item_response_theory"
                target="_blank">Item Response Theory</a>, we can 
                determine how well the exam functions as an assessment 
                tool.  A reliable exam is consistently able to 
                distinguish between high-level learners and low-level 
                learners.
            </p>
        </div>
        
        <div class='question'>
            <a name="q3"></a><h4 class="section-header no-border">Q. How do you determine an exam's predictability?</h4>
            <p class='answer'>
                Instructors that participate in pilot-testing must report 
                their students' National Registry exam results.  With 
                this information, Fisdap analyzes the relationship between 
                passing our exam and passing the National.  For example, 
                when the Online Summative Paramedic Exam (OSPE) was 
                originally released, we discovered that students who 
                received a score of 71% or higher on the OSPE had a 97% 
                chance of passing the Registry.  Instructors are able to 
                access predictability information online.
            </p>
        </div>
        
        <div class='question'>
            <a name="q4"></a><h4 class="section-header no-border">Q. Are Fisdap exams computer adaptive like the National Registry Cognitive Exam?</h4>
            <p class='answer'>
                All Fisdap exams are computer-based tests (CBT); the 
                exams are administered via computer, just like the 
                Registry.  Unlike the Registry exam, however, Fisdap 
                exams are not computer-adaptive.  Each student will 
                answer the same 200 test-items as their peers, 
                although not necessarily in the same order. 
                <br><br>
                For more information about the computer-based testing 
                and computer adaptive testing, visit the 
                <a href='http://www.nremt.org/nremt/about/CBT_home.asp'
                target="_blank">NREMT Website</a>.
            </p>
        </div>
        
        <div class='question'>
            <a name="q5"></a><h4 class="section-header no-border">Q. How do students get their results?</h4>
            <p class='answer'>
                Instructors may retrieve student scores after the exam 
                has been completed.  Students should obtain their 
                scores from their instructors.
            </p>
        </div>

        <div class='question'>
            <a name="q6"></a><h4 class="section-header no-border">Q. Does Fisdap provide feedback on the students' performances?</h4>
            <p class='answer'>
                Students are scored in several topical categories 
                (Airway, Cardiology, ECG (paramedic-only), Medical, 
                Ob-Peds, Operations, Trauma) as well as overall.  
                Additionally, instructors will be able to access exam 
                statistics that include recommended cut scores, 
                national averages, and research results (e.g. the 
                correlation between success on the exam and success 
                on the National Registry).  To maintain the security 
                and integrity of our exams, we do not display the 
                specific test-items that each student missed.  If you 
                are interested in non-secure practice and learning 
                materials, consider purchasing a Fisdap Review account.
            </p>
        </div>
        
        <div class='question'>
            <a name="q7"></a><h4 class="section-header no-border">Q. How do I get my students' National Registry Cognitive Exam results?</h4>
            <p class='answer'>
                Your program director should be able to retrieve the 
                scores from the 
                <a href='http://www.nremt.org' target='_blank'>NREMT Website</a>. 
                If you are participating in Fisdap pilot-testing, we will 
                need to know how many times each student attempted the 
                NREMT Cognitive exam and whether he or she ultimately 
                passed or failed.
            </p>  
        </div>
    </div>
    
    <div class="grid_12">
        <a href="/learning-center">&lt;&lt; Return to Learning Center</a>
    </div>
</div>