
<div id="base-modal"><?= $this->element->base_modal; ?></div>
<div id="merge-bases-modal"><?= $this->element->merge_bases_modal; ?></div>

<div id="add-base-wrapper">
	<?= ($this->element->show_merge) ? "<a href='#' class='add-base " . $this->element->new_button['class'] . "' id='" . $this->element->new_button['modal_launch_id'] . "'></a>" : ""; ?>
</div>

<div id="base-buttons" class="extra-small">
	
	<div class="grid_6">
		<?= ($this->element->show_merge) ? '<a href="#" id="merge-bases">Merge</a>' : ''; ?>
	</div>
	
	<div class="grid_6">
		<?= $this->element->search_bases ?>
	</div>
	
	<div class="clear"></div>
</div>

<div id="no_active_bases_warning" class="notice">
	You must have at least one active <?= $this->element->base_department ?> in order to use this site.
</div>

<div class="all-action-links-bases hide-when-no-accordion">
	<div class="grid_6"><a href="#" id="expand-all-bases">expand all</a> | <a href="#" id="collapse-all-bases">collapse all</a></div>
	<div class="grid_6 activate-bases"><a href="#" id="activate-all-bases">activate all</a> | <a href="#" id="deactivate-all-bases">deactivate all</a></div>
	<div class="clear"></div>
</div>

<div id="base-accordion" class="accordion" data-basedepartment="<?= $this->element->base_department ?>">
	<?= $this->partial("forms/site-sub-forms/base-accordion.phtml", array("form_element" => $this->element)); ?>
</div>

<? if ($this->element->site_type == "clinical") { ?>
	<div class="standard-departments-msg">
		Standard clinical departments are managed by Fisdap and cannot be renamed or merged.
	</div>
<? } ?>