<?php 
/*
<?php echo $this->pageTitleHelper("jQuery UI Widget Page") ?>

<?php $this->tabPane("newstab",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ante diam, tincidunt vel condimentum quis, fringilla et turpis. Ut auctor lacinia urna, at eleifend odio vestibulum vel.",
array('title' => "Section 1")); ?>

<?php $this->tabPane("newstab",
"Sed ut elit in sem cursus viverra bibendum eget lectus. Praesent gravida, ligula sit amet scelerisque interdum, dolor dui sollicitudin nibh, at congue nibh mauris sit amet justo. Ut dictum ornare dignissim.",
array('title' => "Section 2")); ?>

<?php $this->tabPane("newstab",
"Donec vitae metus non eros congue egestas. Vivamus id dolor nec metus tincidunt dictum vel ut arcu. Suspendisse at metus neque, sed ullamcorper risus. Etiam sodales magna a lorem tincidunt porttitor in non magna.",
array('title' => "Section 3")); ?>

<?php $this->accordionPane("newsaccordian",
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ante diam, tincidunt vel condimentum quis, fringilla et turpis. Ut auctor lacinia urna, at eleifend odio vestibulum vel.",
array('title' => "Section 1")); ?>

<?php $this->accordionPane("newsaccordian",
"Sed ut elit in sem cursus viverra bibendum eget lectus. Praesent gravida, ligula sit amet scelerisque interdum, dolor dui sollicitudin nibh, at congue nibh mauris sit amet justo. Ut dictum ornare dignissim.",
array('title' => "Section 2")); ?>

<?php $this->accordionPane("newsaccordian",
"Donec vitae metus non eros congue egestas. Vivamus id dolor nec metus tincidunt dictum vel ut arcu. Suspendisse at metus neque, sed ullamcorper risus. Etiam sodales magna a lorem tincidunt porttitor in non magna.",
array('title' => "Section 3")); ?>

<h2>Date Picker</h2>
<?php echo $this->datePicker("dp1", '', array()); ?>

<div class="clear" style="margin-bottom: 3em;"></div>

<h2>Latest News</h2>
<?php echo $this->tabContainer("newstab",
							   array(),
							   array()); ?>

<div class="clear" style="margin-bottom: 3em;"></div>

<h2>Accordian</h2>
<?php echo $this->accordionContainer("newsaccordian",
									 array(),
									 array("class" => "dark-accordian")); ?>

<div class="clear" style="margin-bottom: 3em;"></div>

<a href="#" id="dark-gray-btn">Test</a>
<a href="#" id="blue-btn">Test</a>
<a href="#" id="green-btn">Test</a>
<a href="#" id="gray-btn">Test</a>
<a href="#" id="orange-btn">Test</a>

<div class="clear" style="margin-bottom: 3em;"></div>

<div id="radioset" class="pick-one-gray-buttons">
	<input type="radio" id="radio1" name="radio" /><label for="radio1">Choice 1</label>
	<input type="radio" id="radio2" name="radio" checked="checked" /><label for="radio2">Choice 2</label>
	<input type="radio" id="radio3" name="radio" /><label for="radio3">Choice 3</label>
</div>

<div class="clear" style="margin-bottom: 3em;"></div>

<div id="radioset2" class="pick-one-orange-buttons">
	<input type="radio" id="radio4" name="radio2" /><label for="radio4">Choice 1</label>
	<input type="radio" id="radio5" name="radio2" /><label for="radio5">Choice 2</label>
	<input type="radio" id="radio6" name="radio2" checked="checked" /><label for="radio6">Choice 3</label>
</div>

*/
?>
Welcome to Fisdap!