<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of graduated
 *
 * @author astevenson
 */
?>
<div class='island'>
	Our records indicate that you <?php echo $this->status ?>.
	You can still view your <a href='/index/Portfolio'>Portfolio</a> and <a href='/reports'>Reports</a>, but you can no longer document additional patient contacts.  
	If this is an error, and you are still actively enrolled in your program, please ask your instructor to update your graduation status.
</div>