<?php
//$this->headTitle('Member Login');

//$this->mainMenu()->setActiveItemId('login');

$form->get('username')->setAttributes([
    'id'=>'username', 
    'required' => true,
	'size' => 15,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class'=>'required'
    ]);

$form->get('password')->setAttributes([
    'id'=>'password',
	'size' => 15,
    'required' => true,
    ])
    ->setLabelAttributes([
        'class'=>'required'
    ]);

$form->get('remember_me')->setAttributes([
    'id'=>'ImSecure', 
    'class' => 'secure'
    ])
    ->setLabelAttributes([
    ]);
?>
<html>
<head>
</head>
<body>
		<div style='width: 1000px; margin: auto;' class="login_page">
			<div class='login_header'>
				<div class='logo'>
					<a href='http://www.<?php echo Util_HandyServerUtils::get_server(); ?>.net/'><img src='/img/Fisdap_logo_new_small.png' width='82' height='35'></a>
				</div>
				<div class='spacer'></div>
			</div>

			<div id='main-content' class='container_12'>
			<h1>Member Login2</h1>
				<div class="row-container">
    <div id='login_area' class="area">
        <form class="form-signin" method="post">
            <d1 class ="zend_form">
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Incorrect login and/or password. 
                <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
            </div>
            <?php endif; ?>
			<div class="login_prompts">
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
			</div></br>
			<div class="login_prompts">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
			</div>
			<div id='my_secure_box_ff' class='form_field secure'> 
            <div class="checkbox">
                <label class="optional">
                    <?= $this->formElement($form->get('remember_me')); ?>I'm secure. Don't ask for my password when I make changes
                </label>
            </div>
			</div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <div class="button_container green-buttons small">
				<div class="grid_8"><a href="#">Forgot your login?</a></div>
				<input name="submit" id="submit" value="Log in" class="ui-button ui-widget ui-state-default ui-corner-all" role="button" aria-disabled="false" type="submit">
			</div>
		</d1>
		</form>
    </div>

    <div id='create_acct' class='area'>
        <h3 class="section-header no-border">Not a member yet?</h3>
        <a href="/account/new/">Create an Account</a>

        <h3 class="section-header no-border">Questions?</h3>
        <a href="https://www.<?php echo Util_HandyServerUtils::get_server(); ?>.net/contact_us">Contact Us</a>

    </div>
</div>

				<div class="clear"></div>
				

					<div class="grid_12 bottomLinks">
						<a href="/privacy" target="_blank">Privacy Policy</a>
						<a href="/terms" target="_blank">Terms of Use</a>
					</div>
					<div class="clear"></div>
				
			</div>
			<?php //echo $this->mainFooter(); ?>
		</div>

		<div id='jquery-dialog-container'></div>
		
  <style>
  .navbar{
	display:none;
  }
 
#main_header{
display: none;
}
  </style>
    <script>
	$(function(){
	var spans = $('.site');
	var spans1 = $('#main-content');
	spans.contents().unwrap();
	spans1.contents().unwrap();
});
	</script>
    </body>
</html>
