<?= $this->pageTitleHelper() ?>
<?= $this->messageHelper() ?>

<div class="grid_12 island">
	<p>Please Note: Student accounts should only be transfered in rare situations. For example, transferring a student from one campus to another.
	Most of the time, a student should be given a new serial number with the same products at the school to which he/she is transferring.
	Don't know the user id or username? Use the <a href='/admin/index/user-search'>user search</a> tool to find it. </p><br />
	
	<?= $this->form ?>			
</div>
