<?= $this->partial('lti/return-link.phtml', null, $this); ?>
<div class="island">
    <div class="section-body">
        You are trying to launch Fisdap from another learning system, but you're already logged in with a different user.
        <br/><br/>Please logout of Fisdap and try again.
    </div>


    <div class='action-button action-buttons'>
		<span class='small green-buttons'>
            <a href='/login/logout' id='logout'>Logout</a>
		</span>
    </div>

    <div class="clear"></div>

</div>