<div class="grid_12">
<div class="new-comment-element">
<?php
	echo $this->element->comment->render();
?>

<?php 
	// echo $this->element->instructor_only->render();
?>
	<br/>Email this comment to:</div> <br />

<?php

	$renderableOthers = array();
	foreach($this->element->otherElements as $oe){
		$renderableOthers[] = $oe->render() . " " . $oe->getLabel();
	}
	
	echo $this->staggeredList($renderableOthers);
?>
<br />

<?php if(count($this->element->instructorElements) > 0){ ?>
	<img id='educator_list_click_closed' src='/images/arrow_right.png' style='width: 15px; height: 15px;' /><img id='educator_list_click_open' src='/images/arrow_down.png' style='width: 15px; height: 15px;' /><span>Educators</span><br/>
	<div class="grid_12" id='educators_list'>
		<?php 
			$renderableInstructors = array();
			foreach($this->element->instructorElements as $ie){
				$renderableInstructors[] = $ie->render() . " " . $ie->getLabel();
			}

			echo $this->staggeredList($renderableInstructors);
		?>
	</div>
	
	<script>
		$(function(){
			$('#educators_list, #educator_list_click_open').hide();
			$('#educator_list_click_closed, #educator_list_click_open').click(function(){ 
				$('#educators_list, #educator_list_click_closed, #educator_list_click_open').toggle();
			});
		});
	</script>
	<br />
<?php } ?>
<div class="grid_12">
	<?php
		echo $this->element->save->render();
		echo $this->element->cancel->render();
	?>
</div>