<div class="ms-picklist-wrapper">
	<div class='picklist-ms-picker'>
		<div class="grid_5">

			<div class="search-available-list">
				<img class="magnifying-glass-icon" src="/images/icons/magnifying-glass.png">
				<input class="search-list" data-listToSearch="available-list">
			</div>


			<h2 id='available-header'>Available <?= ucwords($this->type) ?></h2>
			<select id="available-list" class="available-list" multiple>

				<?php
					if (!empty($this->assignable)) {
						foreach($this->assignable as $id => $name){
							$disabled = '';
							if (in_array($id, $this->assigned)) {
								$disabled = 'disabled="disabled"';
							}
						?>
							<option value="<?= $id ?>" data-itemId="<?= $id ?>" href="#" <?= $disabled ?>><?= $name ?></option>
						<?php
						}
					}
				?>

			</select>

		</div>

		<div class="grid_2">
			<div class="picklist-control-buttons extra-small gray-button">

				<a href="#" data-controlFunction="add" title="Add">&gt;</a>
				<a href="#" data-controlFunction="remove" title="Remove">&lt;</a>
				<a href="#" data-controlFunction="addAll" title="Add all">&gt;&gt;</a>
				<a href="#" data-controlFunction="removeAll" title="Remove all">&lt;&lt;</a>

			</div>
		</div>


		<div class="grid_5">
			<h2 id="chosen-header">Selected <?= ucwords($this->type) ?></h2>
			<select class="chosen-list" id="chosen-list" multiple>

				<?php
					if (!empty($this->assigned)) {
						foreach($this->assigned as $id){
							$name = $this->assignable[$id];
							?>
							<option value="<?= $id ?>" data-itemId="<?= $id ?>" href="#"><?= $name ?></option>
						<?php
						}
					}
				?>

			</select>
		</div>

		<div class="clear">	</div>

	</div>

<input type="hidden" id="longLabel" name="longLabel" value="<?= $this->longLabel ?>">

<?php
// output a hidden element that contains the selected students. This is useful if the form must submit, or values collected via jquery's form.serialize()
$assignedList = (!empty($this->assigned)) ? $this->assigned : array(); 
?>
<input type="hidden" name="multi_picklist_selected" data-legible-value="<?php echo count($assignedList); ?>" data-legible-label=" <?= ucwords($this->type) ?>" value="<?php echo implode(",", $assignedList); ?>" />

</div>
