<?= $this->pageTitleHelper() ?>
<?= $this->tour->guidedTourHelper(1); ?>

<div id="add-base-wrapper">
	<a href="#" class="add-base add-base-clinical" id="new-department-trigger"></a>
</div>

<div class="island" id="guided-tour-test-content">
	
	<h3 class="section-header">consectetur adipisicing</h3>
	
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
	ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
	sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	
	<ul>
		<li>Ut aliquip ex ea commodo consequat.</li>
		<li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</li>
		<li>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui off</li>
	</ul>
	

	<?= $this->form; ?>
	

</div>
