<tr>
    
    <td class="checkboxCell" valign="middle"><input class="inTable" type="checkbox" value="<?= $this->code['number'];?>"></td>
    <td class="codeCell"><?= $this->code['number']?></td>
    <td class="productsCell"><?= $this->code['products']?></td>
    <td class="statusCell"><?= $this->code['availability']?></td>
    <td class="certCell"><?= $this->code['description']?></td>
    <td class="advancedCell"><?= $this->code['advanced']?></td>
    <td class="orderCell"><?= $this->code['order_date']?></td>
    
</tr>