<div id="siteInfo" class='container_12'>
    <h3 class='section-header no-border'>Please choose one name from the list below to represent this preceptor:</h3>

    <div id="radioContainer">
        <?= $this->element->siteId ?>
	
    </div>

    <table class='fisdap-table bases-table clickable' id='preceptor-table'>

    </table>
            
    <div class='buttons'>
	<div id="cancelButtonWrapper" class="small gray-button">
            <a href='#' id='cancel-preceptor-merge-btn'>Cancel</a>
	</div>
    	<div id="preceptorMergeButtonWrapper" class="small green-buttons">
	    <a href='#' id='do-preceptor-merge-btn'>Merge</a>
	</div>
    </div>
        
</div>

	


