<div id="siteInfo">
	<p>If you want to use the Map It! feature in the Skills Tracker, enter an address for this <span id="baseDepartmentText">base</span>.</p>
	<br />
	<?= $this->element->base_name ?>
	<div style="clear:both;"></div>
	
	<?= $this->element->base_address ?>
	<div style="clear:both;"></div>
	
	<?= $this->element->base_city ?>
	<div style="clear:both;"></div>
	
	
	<?= $this->element->base_state ?>
	<?= $this->element->base_zip ?>
	<div style="clear:both;"></div>
</div>

	<div style="clear:both;"></div><br />

	<?= $this->element->base_active ?>
	<?= $this->element->base_siteId ?>
	<?= $this->element->base_id_input ?>
	
	<!--
	<div class="extra-small orange-button">
		<a href="#" id="delete-base-btn">Delete Base</a>
	</div>
	-->
	
	<div id="throbberWrapper">
		
	</div>

