<div id="siteInfo">

	<?= $this->element->preceptor_first ?>
	<div style="clear:both;"></div>
	<?= $this->element->preceptor_last ?>
	<div style="clear:both;"></div>
	<?= $this->element->preceptor_work ?>
	<div style="clear:both;"></div>

	<?= $this->element->preceptor_home ?>

	<div style="clear:both;"></div>
	<?= $this->element->preceptor_pager ?>

	<div style="clear:both;"></div>
	<?= $this->element->preceptor_email ?>

</div>


	<?= $this->element->preceptor_siteId ?>
	<?= $this->element->preceptor_id_input ?>


