<div id="siteInfo">
	<p>All fields are required.</p>
	<br />
	<?= $this->element->site_name ?>
	<div style="clear:both;"></div>
	<?= $this->element->site_abbrev ?>
	<div style="clear:both;"></div>
	<?= $this->element->site_city ?>
	<div style="clear:both;"></div>
	<?= $this->element->site_state ?>
	<div style="clear:both;"></div>
</div>

<div id="typeContainer">
				
				<h3>How will this site be used?</h3>
				
				<div id="radioContainer">
						<?= $this->element->site_type ?>
				</div>
				<img  style="width:20px;" id="field" src="/images/icons/fieldSiteIconColor.png">
				<img  style="width:20px;" id="clinical" src="/images/icons/clinicalSiteIconColor.png">
				<img  style="width:18px;" id="lab" src="/images/icons/labSiteIconColor.png">

				
</div>
	<div style="clear:both;"></div><br />

