<div id="legend" class="grid_12">
	
	<div class="grid_2 legend_col has-borders no-left-border">
		
		<div class="grid_2"><img src="/images/icons/fieldSiteIconColor.png"></div>
		<div class="grid_10">Field site</div>
		
		<div class="clear"></div>
		
		<div class="grid_2"><img src="/images/icons/clinicalSiteIconColor.png"></div>
		<div class="grid_10">Clinical site</div>
		
		<div class="clear"></div>
		
		<div class="grid_2"><img src="/images/icons/labSiteIconColor.png"></div>
		<div class="grid_10">Lab site</div>
		
	</div>
    
    <div class="grid_5 legend_col">
		
		<div class="grid_2"><img src="/images/icons/sharing-admin.png"></div>
		<div class="grid_10">Site admin for shared network</div>
		
		<div class="clear"></div>
		
		<div class="grid_2"><img src="/images/icons/sharing.png"></div>
		<div class="grid_10">Sharing</div>
		
		<div class="clear"></div>
        
        <div class="grid_2"><img src="/images/icons/not-in-network.png"></div>
        <div class="grid_10">Shared network exists
			<br /><span class="tiny-font">not in network or pending approval</span>
		</div>
		
        <div class="clear"></div>

	</div>
</div>