<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of index
 *
 * @author astevenson
 */
?>
<?php if (!$this->contentOnly) { ?>

<h2 class="page-title"><?= $this->student->user->getFullName() ?>'s Portfolio</h2>

<?php echo $this->portfolioNavigation($this->skillstracker, $this->compliance); ?>

<div class='grid_9'>
    <div id="portfolio-page-content" class="island">
        <?php } else { ?>
        <div class='grid_12'>
            <div class="island">
                <?php } ?>
                <div class="grid_7">
                    <h2 class='section-header'>Affective Evaluations</h2>

                    <div class='content'>
                        Note that this list includes evaluations performed by the educatiors, peers,
                        and <?php echo ($this->user->isInstructor()) ? $this->student_name : "yourself"; ?>.
                    </div>
                    <table>
                        <tr>
                            <td class='skill-sheet-header skill-sheet-row-left'>
                                Evaluation Title
                            </td>
                            <td class='skill-sheet-header skill-sheet-row-right'>
                                Average Score
                            </td>
                        </tr>
                        <?php foreach ($this->evalList as $title => $evalData): ?>
                            <tr>
                                <td class='skill-sheet-row-left' width='85%'>
                                    <?php echo $title; ?>
                                </td>
                                <td class='skill-sheet-row-right' width='15%'>
                                    <?php
                                    if ($evalData['total_points'] != 0) {
                                        echo round(($evalData['scored_points'] / $evalData['total_points']) * 100) . "%";
                                    } else {
                                        echo "N\A";
                                    }
                                    ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <div class="grid_5">
                    <h3 class='section-header'>Attendance</h3>
                    <?php $noun = ($this->user->isInstructor()) ? $this->student_name . " was" : 'You were'; ?>

                    <?php echo $noun . " tardy for <span class='shift-count'>" . intval($this->attendanceCounts['Tardy']) . "</span> shift" . (($this->attendanceCounts['Tardy'] == 1) ? '' : 's') . ". <br />"; ?>
                    <?php echo $noun . " absent for <span class='shift-count'>" . intval($this->attendanceCounts['Absent']) . "</span> shift" . (($this->attendanceCounts['Absent'] == 1) ? '' : 's') . ". <br />"; ?>
                    <?php echo $noun . " absent with permission for <span class='shift-count'>" . intval($this->attendanceCounts['Absent with Permission']) . "</span> shift" . (($this->attendanceCounts['Absent with Permission'] == 1) ? '' : 's') . ". <br /><br />"; ?>

                    <h3 class='section-header'>Evaluation Progress</h3>

                    <div class='content'>
                        Visit the <a href='#' class='launch-report-config' data-studentid='<?= $this->student->id ?>'
                                     data-reporttype='GraduationRequirements'>Graduation Requirements report</a> to see
                        whether <?php echo ($this->user->isInstructor()) ? $this->student_name . " is" : "you are"; ?>
                        meeting the programs skill, patient, and evaluation requirements.
                    </div>

                    <h3 class='section-header'>Complete Evaluation Archive</h3>

                    <div class='content'>
                        View all of <?php echo ($this->user->isInstructor()) ? $this->student_name . "'s" : "your"; ?>
                        <a href='<?php echo $this->reportURL; ?>'> Evals & Skill Sheets</a>.
                    </div>
                </div>
            </div>
        </div>