<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of index
 *
 * @author astevenson
 */
?>
<script>
	var modalOptions = {
		modal: true,
		resizable: false,
		draggable: false,
		width: 600
	}
	
	confirmDelete = function(id, title){
		modalOptions.buttons = {
			'Delete' : function() {
				window.location = '/portfolio/index/delete-attachment/docId/' + id;
			},
			'Cancel' : function() {
				$(this).dialog('close');
			}
		};
		
		$('<div>Are you sure that you want to delete "' + title + '"?  This action cannot be undone.</div>').dialog(modalOptions);
		
		return false;
	};
	
	$(function(){
		$('#upload-file-btn').click(function(){
			if($('#file').val() == ''){
				modalOptions.buttons = {
					'OK' : function() {
						$(this).dialog('close');
					}
				}
				
				$('<div>Please select a file to upload.</div>').dialog(modalOptions);
				
				return false;
			}else{
				return true;
			}
			console.log($('#file').val());
			
		});
	});
</script>

<?php if(!$this->contentOnly) { ?>

	<h2 class="page-title"><?= $this->student->user->getFullName() ?>'s Portfolio</h2>

	<?php echo $this->portfolioNavigation($this->skillstracker, $this->compliance); ?>

	<div class='grid_9'>
		<div id="portfolio-page-content" class="island">
<?php } else { ?>
	<div class='grid_12'>
		<div class="island">
<?php } ?>
		<h2 class='section-header'>Attachments</h2>
		<br />
		<?php if(($this->user->isInstructor() && $this->user->hasPermission("Edit Portfolio")) || !$this->user->isInstructor()): ?>
			<h3 class='section-header no-border'>Upload a new file</h3>
			<?php echo $this->form; ?>
			<br />
		<?php endif; ?>
		
		<?php foreach($this->uploads as $upload){ ?>
			<div class='grid_12 attachment-header'>	
				<div class='grid_11'>
					<div class='attachment-name'><?php echo $upload->original_name; ?></div>
					<span class='attachment-details'>Uploaded <?php echo $upload->created->format('m-d-Y'); ?> by <?php echo $upload->uploader->first_name . " " . $upload->uploader->last_name; ?></span>
				</div>
				<div class='grid_1 attachment-delete'>
					<?php if($this->canDelete){ ?>
						<a href='#' onclick='return confirmDelete(<?php echo $upload->id; ?>, "<?php echo $upload->original_name; ?>")'><img src='/images/icons/delete.png' width='40' height='40' title='Delete <?php echo $upload->original_name; ?>'/></a>
					<?php } ?>
				</div>
			</div>
			
			<div class='grid_12 attachment-description'>
				<?php echo $upload->description; ?>
			</div>
		
			<div class='grid_12 attachment-download'>
				<a href='/portfolio/index/download-attachment/docId/<?php echo $upload->id; ?>'>Download <?php echo $upload->original_name; ?></a>
			</div>
		<?php } ?>
	</div>
</div>