<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of portfolio compliance
 *
 * @author khanson
 */
?>


<? if (!$this->contentOnly) { ?>

<?= $this->tour->guidedTourHelper($this->tour_id); ?>

<h2 class="page-title"><?= $this->student->user->getFullName() ?>'s Portfolio</h2>
<?= $this->portfolioNavigation($this->skillstracker, $this->compliance); ?>

<div class='grid_9'>
    <?= $this->navBar("portfolio"); ?>
    <div id="portfolio-page-content" class="island">
        <? }
        else { ?>
        <div class='grid_12'>
            <div class="island">
                <? }
                $sentence_fragment = ($this->user->isInstructor()) ? $this->student_name . " is" : "You are";
                ?>
                <h3 class='section-header'>Compliance Status</h3>

                <div class='clear'></div>

                <div id='statusDiv' class="grid_12">


                    <div class="grid_6">
                        <div class="text" id="portfolio-compliance-status-summary">
                            <?= $sentence_fragment ?> <span class='status in-progress-status'>in progress</span> for
                            <?= count($this->pending_attachments) ?> <?= Util_String::pluralize('requirement', count($this->pending_attachments)) ?>
                            and <span class='status non-compliant-status'>non-compliant</span> for
                            <?= count($this->non_comp_attachments) ?> <?= Util_String::pluralize('requirement', count($this->non_comp_attachments)) ?>.
                            <div class="clear"></div>
                        </div>

                        <div class='clear'></div>

                    </div>


                    <div class="grid_6 cleared-grid">
                        <div class="text">
                            <?= $sentence_fragment ?>
                            <?
                            if (count($this->sites) > 0) {
                                echo " cleared to go to " . count($this->sites) . " site";
                                echo (count($this->sites) != 1) ? "s." : ".";
                            } else {
                                echo " not cleared to go to any sites.";
                            }
                            ?>
                        </div>
                        <div class='clear'></div>
                    </div>

                    <div class='clear'></div>
                    <br/>

                    <div class="grid_6">
                        <div id="emailButtonWrapper" class="extra-small gray-button">
                            <? if ($this->user->isInstructor() && (count($this->pending_attachments) + count($this->non_comp_attachments) > 0)) { ?>
                                <a href='#' id='send-req-email'
                                   data-usercontextid='<?= $this->student->user_context->id ?>'>Send email</a>
                            <? } ?>
                        </div>
                    </div>

                    <?
                    if (count($this->sites) > 0) { ?>
                        <div class="grid_6 cleared-grid">
                            <div id="siteButtonWrapper" class="extra-small gray-button">
                                <a href='#' id='launch-site-list'
                                   data-usercontextid='<?= $this->student->user_context->id ?>'
                                   data-siteids="<?= implode(',', $this->sites) ?>">See list</a>
                            </div>
                        </div>
                    <? } ?>

                    <div class='clear'></div>

                </div>
                <div class='clear'></div>

                <div class="dotted-line">
                    <hr>
                </div>

                <div id='status-filter' class="extra-small">
                    <input type='radio' id='all-reqs' name='status_type' checked='checked'><label
                        for='all-reqs'>All</label>
                    <input type='radio' id='pending' name='status_type'><label for='pending'>In Progress</label>
                    <input type='radio' id='compliant-only' name='status_type'><label
                        for='compliant-only'>Compliant</label>
                    <input type='radio' id='non-compliant-only' name='status_type'><label for='non-compliant-only'>Non-Compliant</label>
                </div>

                <h3 id='requirements-header'><span id='requirements-header-text'>Requirements</span></h3>

                <div class='clear'></div>

                <div id='attachmentsAccordion'>
				<?php $user_context = \Fisdap\EntityUtils::getEntity("UserContext", $this->student->user_context->id);		?>
                    <?= $this->userComplianceAccordion($user_context, 'all-reqs', $this->req_associations) ?>
                </div>

            </div>
        </div>

        <?= $this->complianceEmailModal() ?>
        <?= $this->clearedSitesModal() ?>
