<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * This is the about page for the portfolio, it gives an overview of the student and some very basic info on their internship progress
 *
 * @author khanson
 */
?>

<? if(!$this->user->isInstructor()){ ?>
	<script>window.location = '/portfolio/index/about'</script>
<? }else{ ?>
	<!-- Display student picker if the user is an instructor -->
	<h2 class="page-title">Student Portfolios</h2>
	<div class="find-student-container island grid_12">
		<h3 class='section-header'>Select a student</h3>
		<?= $this->studentPicker ?>
	</div>
<? } ?>
