<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of index
 *
 * @author astevenson
 */
?>
<?php if(!$this->contentOnly) { ?>

	<h2 class="page-title"><?= $this->student->user->getFullName() ?>'s Portfolio</h2>

	<?php echo $this->portfolioNavigation($this->skillstracker, $this->compliance); ?>

	<div class='grid_9'>
		<div id="portfolio-page-content" class="island">
<?php } else { ?>
	<div class='grid_12'>
		<div class="island">
<?php } ?>
		<div class="grid_7">
			<h2 class='section-header'>Lab Practice</h2>
			<div class='content'>
				<?php echo ($this->user->isInstructor())?$this->student_name . " has":"You have";	?> successfully performed the following skills.  Note that this list includes only skills that were evaluated by a peer or instructor.
			</div>
			<table>
				<tr>
					<td class='skill-sheet-header skill-sheet-row-left'>
						Practice Item
					</td>
					<td class='skill-sheet-header skill-sheet-row-right'>
						# Passes
					</td>
				</tr>
				
				<?php foreach($this->passedItems as $title => $passCount): ?>
					<tr>
						<td class='skill-sheet-row-left' width='85%'>
							<?php echo $title; ?>
						</td>
						<td class='skill-sheet-row-right' width='15%'>
							<?php echo $passCount; ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</table>
			<br>
			<table>
				<tr>
					<td class='skill-sheet-header skill-sheet-row-left'>
						Scenario Topic Area
					</td>
					<td class='skill-sheet-header skill-sheet-row-right'>
						# Passes
					</td>
				</tr>
				<?php foreach($this->topicAreas as $topic => $count): ?>
					<tr>
						<td class='skill-sheet-row-left' width='85%'>
							<?php echo $topic; ?>
						</td>
						<td class='skill-sheet-row-right' width='15%'>
							<?php echo $count; ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<div class="grid_5">
			<h3 class='section-header'>Lab Shifts</h3>
			<div class='content'>
				<?php echo ($this->user->isInstructor())?$this->student_name . " has":"You have";	?> attended <?php echo $this->labShiftCounts; ?> lab shifts and completed <?php echo $this->labShiftHours; ?> hours of lab practice.
			</div>
			<h3 class='section-header'>Program Goal Progress</h3>
			<div class='content'>
				View <?php echo ($this->user->isInstructor())?$this->student_name . "'s":"your";	?> <a href='#' class='launch-report-config' data-studentid='<?= $this->student->id ?>' data-reporttype='LabPracticeGoals'>Lab Practice report</a> for more detailed info.
			</div>
			
			<h3 class='section-header'>Complete Evaluation Archive</h3>
			<div class='content'>
                View all of <?php echo ($this->user->isInstructor())?$this->student_name . "'s":"your";	?> <a href='<?php echo $this->reportURL; ?>'> Evals & Skill Sheets</a>.
			</div>
		</div>
	</div>
</div>