<?= $this->element->preceptor_id; ?>

<?= $this->element->preceptor_first; ?><div class="clear"></div>
<?= $this->element->preceptor_last; ?><div class="clear"></div>

<?= $this->element->preceptor_work; ?><div class="clear"></div>
<?= $this->element->preceptor_home; ?><div class="clear"></div>
<?= $this->element->preceptor_pager; ?><div class="clear"></div>
<?= $this->element->preceptor_email; ?><div class="clear"></div>

<div id="preceptor-modal-buttons" class="small">
	
	<div class="green-buttons">
		<a href="#" id="save-preceptor-modal">Save</a>
	</div>
		
	<a href="#" id="cancel-preceptor-modal">Cancel</a>
	
</div>