<div class='hidden'>
	<?= $this->element->staff_member_id; ?>
	<div class="clear"></div>
</div>

<?= $this->element->staff_member_first; ?><div class="clear"></div>
<?= $this->element->staff_member_last; ?><div class="clear"></div>
<?= $this->element->staff_member_title; ?><div class="clear"></div>

<?= $this->element->staff_member_phone; ?><div class="clear"></div>
<?= $this->element->staff_member_pager; ?><div class="clear"></div>
<?= $this->element->staff_member_email; ?><div class="clear"></div>
<?= $this->element->staff_member_bases; ?><div class="clear"></div>
<?= $this->element->staff_member_notes; ?>
<div class="notes-description optional-field">(200 characters max)</div>
<div class="clear"></div>

<div id="staff-member-modal-buttons" class="small modal-buttons">
	
	<div class="green-buttons">
		<a href="#" id="save-staff-member-modal">Save</a>
	</div>
		
	<a href="#" id="cancel-staff-member-modal">Cancel</a>
	
</div>