<?= $this->pageTitleHelper() ?>
<?= $this->messageHelper() ?>

<div class="grid_12 island">

	<div class="grid_6">
		<a href="/account/orders/account-holders">Buy new accounts</a><br />
		Whether you are paying or they are, order new activation codes for students and preceptors.
	</div>
	
	<div class="grid_6 prefix 1">
		<a href="/account/orders/upgrade">Upgrade existing accounts</a><br />
		If you'd like to order additional product access for your students, you can upgrade their accounts.
	</div>
	
			
	<div class="grid_6 needMargin">
		<a href="/account/orders/inventory">View my inventory (unused activation codes)</a><br />
		Search for specific activation codes or find ones that have not been activated and are still available.
	</div>
	
	<div class="grid_6 needMargin">
		<a href="/account/orders/history">View my order history</a><br />
		Reference-and even repeat-your past orders.
	</div>

	
	<div style="clear:both"></div>
</div>