<?= $this->pageTitleHelper() ?>
<div class="grid_12 island">
    <p>
        <?= $this->directions ?>
    </p>
    <br>
    
    <p>
        Products for your students: <?= $this->studentsDescription ?>
    </p>
    
    <?= $this->form ?>
    
    <div class="alpha grid_4">
        <a href='/account/orders/packages'>&lt;&lt; Previous (Products: Packages)</a>
    </div>
    
    <div class="prefix_4 grid_4">
        <a href="#" id="next-link">Next (Order Summary) &gt;&gt;</a>
    </div>
</div>