<?= $this->doctype() ?>

<html lang="en">
    <head>
	<?php
	echo $this->headTitle($this->headTitleHelper());
		
		$header = $this->mainHeader(); ?>
        <meta charset="utf-8">
        <?= $this->headTitle('Fisdap')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
				  ->appendHttpEquiv('Content-Language', 'en-US')
				  ->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
	<div class="site">
	<div id='main_header' class='main_header'>
				<div id='header_nav' class='header_nav'>
					<div id='header_upper_nav'>
						<a href='https://www.fisdap.net'><div id='site-title'>FISDAP</div></a>
						<div id='user_info' class='user_info'> <?php echo "Test".$this->view->profileLink()?></div>
						<div class='clear'></div>
						<div id='subtitle'> Online Tools for <?php echo $profession; ?> Education${releaseStageHtml}</div><div class='clear'></div></div>
						
						

       <ul class="main_navigation">
    <li class="active">
        <a title="MyFisdap" href="/my-fisdap" style="position: relative; top: 2px;">MyFisdap</a>
        
    </li>
    <li>
        <a title="Shifts" href="/skills-tracker" style="position: relative; top: 2px;">Shifts</a>
        <ul style="text-align: center; width: 225px; position: absolute; top: 112px; left: 117.35px; display: none;">
            <li>
                <a href="/scheduler">Schedule</a>
            </li>
            <li>
                <a href="/skills-tracker/shifts">Skills &amp; Pt. Care</a>
            </li>
        </ul>
    </li>
    <li>
        <a title="Learning Center" href="/learning-center" style="position: relative; top: 2px;">Learning Center</a>
        <ul style="text-align: center; width: 255px; position: absolute; top: 112px; left: 241.2px; display: none;">
            <li>
                <a href="/learning-center/index/schedule">Test Schedule</a>
            </li>
            <li>
                <a href="/learning-center/index/retrieve">Retrieve Scores</a>
            </li>
        </ul>
    </li>
    <li>
        <a title="Reports" href="/reports/index/splash" style="position: relative; top: 2px;">Reports</a>
        <ul style="text-align: center; width: 230px; position: absolute; top: 112px; left: 392.55px; display: none;">
            <li>
                <a href="/reports/index/legacy">Evals &amp; Skill Sheets</a>
            </li>
            <li>
                <a href="/reports">Reports</a>
            </li>
        </ul>
    </li>
    <li>
        <a title="Account" href="/account" style="position: relative; top: 2px;">Account</a>
    </li>
    <li>
        <a title="Community" href="/community" style="position: relative; top: 2px;">Community</a>
    </li>
    <li>
        <a title="Help" href="/help" style="position: relative; top: 2px;">Help</a>
    </li>
</ul>
		</div>
		</div>
        <div id="main-content" class="container_12">
            <?= $this->content ?>
			</div>
           <div id='footer' class='footer'>
				<div id='footer_text' class='footer_text'>
					651-690-9241
					<span class='footer_separator'>|</span>
					
					<a href='mailto:info@fisdap.net'>info@fisdap.net</a>
				</div>
			</div>
		</div>
    </body>
</html>
