Hello!
<div>
	<div>
		You have been assigned to <?= count($this->events)." ".$this->events[0]->type ?> shifts
		at:
	</div>
	<div style='margin: 1em 0em'>
		<?= $this->events[0]->getLocation() ?><br>
		<?= $this->events[0]->start_datetime->format("Hi") . " (" . $this->events[0]->getDurationText() . ") " ?>
		<?= ($this->events[0]->notes) ? "<br />Notes: " . $this->events[0]->notes : ""; ?>
	</div>
	<div>
		These shifts will occur on the following dates:
		<ul>
			<?php foreach ($this->events as $event) { ?>
			<li><?= $event->start_datetime->format('l, M j, Y') ?></li>
			<?php } ?>
		</ul>
	</div>
</div>
