<p>This person has registered for the EMS Ride:</p>
<br>
	
    <p class='firstName'>
       First Name:  <?= $this->item->first_name ?>
    </p>
	
    <p class='lastName'>
       Last Name: <?= $this->item->last_name ?>
    </p>
	
    <p class='address1'>
       Address Line 1: <?= $this->item->address1 ?>
    </p>	

    <p class='address2'>
       Address Line 2: <?= $this->item->address2 ?>
    </p>
	
    <p class='city'>
       City: <?= $this->item->city ?>
    </p>
	
    <p class='state'>
       State: <?= $this->item->state ?>
    </p>

    <p class='zipcode'>
       Zipcode: <?= $this->item->zipcode ?>
    </p>
	
    <p class='email'>
       Email: <?= $this->item->email ?>
    </p>
	
    <p class='homePhone'>
       Home Phone: <?= $this->item->home_phone ?>
    </p>
	
    <p class='workPhone'>
       Work Phone: <?= $this->item->work_phone ?>
    </p>	

    <p class='cellPhone'>
       Cell Phone: <?= $this->item->cell_phone ?>
    </p>
	
    <p class='emContact'>
       Emergency Contact: <?= $this->item->emergency_contact ?>
    </p>
	
    <p class='emRel'>
       Emergency Relation: <?= $this->item->emergency_relation ?>
    </p>
	
    <p class='emPhone'>
       Emergency Phone: <?= $this->item->emergency_phone ?>
    </p>

    <p class='role'>
       Role: <?= $this->item->role->name ?>
    </p>
	
    <p class='days'>
       Days Participating: <?= $this->item->days ?>
    </p>
	
    <p class='jersey'>
       Jersey Size: <?= $this->item->jersey_size ?>
    </p>

    <p class='shirt'>
       Shirt Size: <?= $this->item->shirt_size ?>
    </p>
	
    <p class='special'>
       Special Needs: <?= $this->item->special_needs ?>
    </p>
	
    <p class='why'>
       Why Participate?: <?= $this->item->why_ride ?>
    </p>
	
    <p class='suggestions'>
       Comments And Suggestions: <?= $this->item->suggestions ?>
    </p>

