Hello <?= $this->passwordReset->user->first_name ?>,<br />
<p style="margin-top:2em">
	Need a little help logging in to Fisdap?</p>


<p>Your Fisdap username is: <b><?= $this->passwordReset->user->username ?></b>.</p>

<p>
	If you cannot remember your password and need to reset it, use this link:<br />
	<?= $this->urlRoot . "account/help/reset-password/code/" . $this->passwordReset->code; ?>
</p>

<p>Please note, this link will expire in 24 hours.</p>
