Hello <?= $this->user->first_name ?>,<br>
	
<p>We are about to begin converting your program to the new version of the Scheduler. We expect this process to take no more than a couple of hours. If you log in to Fisdap during the conversion, you will see the new interface, but you may not see all your shifts yet. 

You will receive another email once your program has finished converting at which point all your information should be updated and visible in the new Scheduler.</p>

<p>If you are part of a sharing network, please be aware that the other members of your network are also being converted today. We advise that you wait until tomorrow to make any changes to your sharing network or shared shifts. If you have any questions, please give us a call at 651.690.9241 and our support staff will assist you.</p>