<p>
	You have been approved to share shifts with <?= $this->site ?>.<br> 
	Students in your program will now be able to pick or be assigned shifts in the Fisdap scheduler 
	that <?= $this->site ?> has made available to them. 
	These shifts will begin to appear in the scheduler as they are made available.<br>
	If you have questions about this, please contact <?= $this->name ?> at <?= $this->email ?>.
</p>
