Hello, <?= $this->request->recipient->user->first_name ?>!
<div>
		<p><?= $this->request->owner->user->getName() ?> has declined your offer to swap the following <?= $this->swap->offer->slot->event->type ?> shift:</p>
		<div>
				<?= $this->swap->offer->slot->event->getDetailViewDate() ?><br>
				<?= $this->swap->offer->slot->event->getLocation() ?>
		</div>
		<p>in exchange for <?= $this->request->owner->user->first_name ?>'s <?= $this->request->event->type ?> shift:</p>
		<div>
				<?= $this->request->event->getDetailViewDate() ?><br>
				<?= $this->request->event->getLocation() ?>
		</div>
		
		<p>
		You can make a new offer or decline the swap from your <a href='<?= $this->url ?>'>shift request page</a>.
		</p>
	
</div>
