<div>
		<p><?= $this->initiator->getName() ?> has removed <?= $this->recipient->getContextualName() ?> from the following <?= $this->event->type ?> shift:</p>
		<div>
			<?= $this->event->getDetailViewDate() ?><br>
			<?= $this->event->getLocation() ?>
		    <?= ($this->event->notes) ? "<br />Notes: " . $this->event->notes : ""; ?>
            <div><?= $this->event->getPreceptorText(); ?></div>
            <div><?= $this->event->getInstructorText(); ?></div>
            <?= $this->event->getStudentSlotText(true); ?>
		</div>
</div>
