Hello, <?= $this->request->recipient->user->first_name ?>!
<div>
<?php 	switch ($this->request->request_type->name) {
		case "cover": ?>
			<p>You agreed to cover the following <?= $this->request->event->type ?> shift for <?= $this->request->owner->user->getName() ?>:</p>
<?php			break;
		case "swap":
		        $swap = $this->request->getCurrentSwap();	?>
			<p>You agreed to swap the following <?= $swap->offer->slot->event->type ?> shift with <?= $this->request->owner->user->getName() ?></p>
			<div>
				<?= $swap->offer->slot->event->getDetailViewDate() ?><br>
				<?= $swap->offer->slot->event->getLocation() ?>
			</div>
			<p>in return for <?= $this->request->owner->user->first_name ?>'s <?= $this->request->event->type ?> shift:</p>
<?php			break;
	} 	?>
	
	<div>
		<?= $this->request->event->getDetailViewDate() ?><br>
		<?= $this->request->event->getLocation() ?>
	</div>
	
	<p>However, the <?= $this->request->request_type->name ?> request has been denied.
<?php 	if ($this->request->request_type->name == 'cover') {	?>
		You are not responsible for this shift.</p>
<?php
	} else {	?>
		You are still responsible for your original shift.
<?php
	}	?>
</div>
