<div class="info hidden_students">

        <b><a href='#' id='hiddenStudentLink'>Where did my students go?</a></b>
        <div id='hiddenStudentInfo'>
                Your students will not appear in the Available Students list if:
                <ul>
                        <li id='no-scheduler'>their accounts do not include access to Scheduler.</li>
                        <li id='assign-to-req-msg'>they have already been assigned to this requirement.</li>
                </ul>
        </div>
</div>