<div class="info hidden_students">

        <b><a href='#' id='hiddenStudentLink'>Where did my students go?</a></b>
        <div id='hiddenStudentInfo'>
                Your students will not appear in the Available Students list if:
                <ul>
                        <li id='no-scheduler'>their accounts do not include access to Scheduler.</li>
                        <li id='cert-requirements'>they cannot go based on their certification level or student group.</li>
                        <li id='shift-limits'>they hit the maximum number of shifts they can attend.</li>
                </ul>
        </div>
</div>

<div class="notice drop-only-students">
        Students with an * next to their name may be dropped from this shift, but cannot be re-assigned.
</div>

<div class="notice has-data-other-program">
        Some students may not be dropped from this shift because they're from a different program and have already entered data.
</div>

<div class="notice has-data">
        The selected students have data entered for this shift that will be deleted if you drop them.
</div>
