<?php
	$request = $this->request;
	$user = \Fisdap\Entity\User::getLoggedInUser();
?>

<tr>
	<td class="sent" style='border-left-style:hidden;border-right-style:hidden'>
		<div class='top'><?= $request['date'] ?></div>
	</td>
	
	<td class="request" style='border-left-style:hidden;border-right-style:hidden'>
		<div class='top'><?= $request['request'] ?></div>
	</td>
	
	<td class="name" style='border-left-style:hidden;border-right-style:hidden'>
		<div class='top'><?= $request['person'] ?></div>
	</td>
	
	<td class="shift" style='border-left-style:hidden;border-right-style:hidden'>
		<img id='site-icon' class='icon' src='/images/icons/<?= $request['event_type'] ?>SiteIconColor.png'>
		<h4 class='<?= $request['event_type'] ?>'><?= $request['event_date'] ?></h4>
		<h4 class='header' style='margin: 0 0 5px 30px'><?= $request['event_location'] ?></h4>
		<div class='additional-shift-info'><?= $request['addl-info'] ?></div>
	</td>
	
	<td class="status" style='border-left-style:hidden;border-right-style:hidden'>
		<?= $request['status'] ?>
	</td>
	
	<td class="tools" style='border-left-style:hidden;border-right-style:hidden'>
		<?= $request['tools'] ?>
	</td>
</tr>
