<?php
/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */
?>

<script>
    $(function(){
        $('.report-table').tableScroll({height:250, width: 850});

        $('.report-table tbody tr:odd').css('background-color', '#C8C8C8');
        $('.report-table tbody tr:even').css('background-color', '#E6E6E6');

        $('.report-table tbody tr').each(function (index, el){ $(el).children().first().css('text-align', 'left') });

        $('.tablescroll_wrapper').css('overflow-x', 'hidden');
    });
</script>

<?php echo $this->javascriptHelper('library/Fisdap/Utils/create-pdf.js'); ?>
<script>
    function createGoalsReportPDF(divId, pdfName){
        pdfName = $("h1").text().replace('.', '-') + ".pdf";
        divContents = $('#' + divId).clone();

        divContents.find(".tablescroll_wrapper").css('height', 'auto');

        return createPdf(divContents, pdfName)
    }
</script>

<div id="goalsReport"><?php
    if ($this->student) {
        // <h2>STUDENT'S GOAL'S REPORT</h2>
        echo $this->goalResultsOneStudent($this->goal, $this->goalResults, $this->heading);
    } else {
        echo $this->goalResultsMultipleStudents($this->goal, $this->goalResults, $this->heading);
    }
    ?></div>