	<?= $this->pageTitleHelper() ?>
	<div class="grid_12 island">
		Our records indicate that you have graduated. You can still view your <a href='/index/Portfolio'>Portfolio</a> and <a href='/reports'>Reports</a>, but you cannot access the shift schedule.<br>  
                If this is an error, and you are still actively enrolled in your program, please ask your instructor to update your graduation status.
	</div>

