<?php if ($this->element->legacy) { ?>
	<div>
<?php } else { ?>
	<?= $this->pageTitleHelper() ?>
	<div class="grid_12 island">
<?php } ?>
		The content you are trying to access is a feature of our new Scheduler.<br>
		To be considered for participation in a limited beta group and to be among the first to get new Scheduler,
		please fill out this
		<a href='https://docs.google.com/a/fisdap.net/forms/d/14_GptQelZu4iZ8umrAvqhCXdbsFM0U31MKhVL94wtWI/viewform' target='_new'>form</a>.
	</div>
