<select multiple="multiple" style="width:300px; height:200px; padding:0.25em">
	
	<option style="padding:0.5em;background-image:url(/images/icons/fieldSiteIconColor.png);background-repeat:no-repeat; background-position:right;">Background Image</option>
	<option style="padding:0.5em;background-color:yellow">Background Color</option>
	<option style="padding:0.5em;font-weight:bold;">Bolded Text</option>
	<option style="padding:0.5em;color:red">Font Color</option>
	<option style="padding:0.5em;opacity:0.6">Opacity</option>
	
</select>