<div id="emails-wrapper">
    <?= $this->pageTitleHelper() ?>
    
    <?= $this->navBar("recurring_emails"); ?>
        
    <div class="grid_12 island">
        <h3 class='section-header'><?= $this->program->name ?>'s Recurring Emails</h3>

<?php if (count($this->emails) > 0): ?>
        <div id='email-table' class='accordion-table'>
            
    <?
    /** @var Fisdap\Entity\ScheduleEmail $recurring_email */
    foreach ($this->emails as $recurring_email):
        $checked = $recurring_email->active ? "checked='checked'" : "";
        $filterInfo = $recurring_email->filter->getInfoArray();

        $userNotice = '';
        $userDeleted = false;
        $isStaff = Fisdap\Entity\User::getLoggedInUser()->isStaff();

        if ($recurring_email->instructor->user->deleted === true) {
            $userDeleted = true;
            $userNotice = "(deleted)";
        }
    ?>
    
            <div class='recurring-email accordion-header-bar'>
                <div class='email-header email-info' id='header-<?= $recurring_email->id ?>'>
                    <img class='accordion-arrow' id='arrow-<?= $recurring_email->id ?>' src='/images/accordion_arrow_right.png'>
                    <?php if (strlen($recurring_email->title) > 44): ?>
                    <a title="<?= $recurring_email->title ?>"><?= str_limit($recurring_email->title, 44) ?></a>
                    <?php else: ?>
                    <?= $recurring_email->title ?>
                    <?php endif; ?>
                </div>

                <div class='email-controls'>
                    <div class='email-active'>
                        <input <?= $userDeleted && $isStaff ? 'disabled=disabled' : '' ?> type='checkbox' class='slider-checkbox' id='active-<?= $recurring_email->id ?>' <?= $checked ?>>
                    </div>

                    <div class='email-actions'>
                        <div class='extra-small gray-button edit-btn-div'>
                            <a href="#" title="edit email" data-emailid="<?= $recurring_email->id ?>" data-emailViewType="<?= $recurring_email->filter->view_type->name ?>" class="edit-recurring-email">Edit</a>
                        </div>
                        <div class="delete-recurring-email" data-emailid="<?= $recurring_email->id ?>">
                            <a title="delete email" href="#">
                                <img class="small-icon" src="/images/icons/delete.png">
                            </a>
                        </div>

                    </div>
                </div>

                <div class='email-user email-info description' id='head-u-<?= $recurring_email->id ?>'>
                    from: <?= "{$recurring_email->instructor->user->first_name} {$recurring_email->instructor->user->last_name} $userNotice" ?>
                </div>




            </div>
    
            <div class='email-details' id='info-<?= $recurring_email->id ?>'>
                <div colspan=3>
                    <h6 class='dark-gray email-summary'>
                        Send <?= $recurring_email->recurring_type ?> long schedule in <?= $recurring_email->filter->view_type->name ?>
                         view to:
                        
                        <?= $recurring_email->email_list ?>, 
                        <?= $recurring_email->offset_number ?> <?= Util_String::pluralize($recurring_email->offset_type, $recurring_email->offset_number, $recurring_email->offset_type."s") ?>
                        in advance with these shifts:
                        
                    </h6>
                    <table class="accordion-info">
                        <tr>
                            <td class="accordion-summary">
                                <h6 class="dark-gray column-header">Location:</h6>
                                <table class="fisdap-table">
                                    <tr><td class='clickable'>
                                        <?= $filterInfo['site_category'] ?>
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['sites'] as $type => $sites) {
                                                $type = lcfirst($type);
                                                foreach ($sites as $site) {
                                                    echo "<li class='$type'>$site</li>";
                                                }
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    
                                    <tr><td class='clickable'>
                                        <?= $filterInfo['base_category'] ?>
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['bases'] as $site => $bases) {
                                                if(count($bases) > 0) {
                                                    if(is_numeric($site)){ $site = \Fisdap\EntityUtils::getEntity('SiteLegacy', $site)->name; }
                                                    echo "<h6 class='dark-gray site-title'>$site</h6>";
                                                    foreach ($bases as $base) {
                                                        echo "<li>$base</li>";
                                                    }
                                                }
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    
                                    <tr><td class='clickable'>
                                        <?= $filterInfo['preceptor_category'] ?>
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['preceptors'] as $site => $preceptors) {
                                                if(count($preceptors) > 0) {
                                                    echo "<h6 class='dark-gray site-title'>$site</h6>";
                                                    foreach ($preceptors as $preceptor) {
                                                        echo "<li>$preceptor</li>";
                                                    }
                                                }
                                            } ?>
                                            </ul>
                                    </td></tr>
                                </table>
                            </td>
                            
                            
                            <td class="accordion-summary">
                                <h6 class="dark-gray column-header">Available to:</h6>
                                <?php if (!$filterInfo['available']) { ?>
                                Not showing available shifts.
                                <?php } else { ?>
                                <table class="fisdap-table">
                                    <?php if ($filterInfo['all_available_certs']) { ?>
                                    <tr><td>All certifications</td></tr>
                                    <?php } else { ?>
                                    <tr><td class='clickable'>
                                        <?= count($filterInfo['available_certs']) ?> <?= Util_String::pluralize("certification", count($filterInfo['available_certs'])) ?> 
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['available_certs'] as $certification) {
                                                echo "<li>$certification</li>";
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    <?php } ?>
                                    
                                    <tr><td class='clickable'>
                                        <?= $filterInfo['available_groups_category'] ?>
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['available_groups'] as $group) {
                                                echo "<li>$group</li>";
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    
                                    <tr><td><?= $filterInfo['hide_invisible'] ? "Hide invisible shifts" : "Show invisible shifts" ?></td></tr>
                                    
                                </table>
                                <?php } ?>
                            </td>
                            
                            
                            <td class="accordion-summary">
                                <h6 class="dark-gray column-header">Chosen by/Assigned to:</h6>
                                <?php if (!$filterInfo['chosen']) { ?>
                                Not showing chosen/assigned shifts.
                                <?php } else { ?>
                                <table class="fisdap-table">
                                    <?php if ($filterInfo['all_chosen_certs']) { ?>
                                    <tr><td>All certifications</td></tr>
                                    <?php } else { ?>
                                    <tr><td class='clickable'>
                                        <?= count($filterInfo['chosen_certs']) ?> <?= Util_String::pluralize("certification", count($filterInfo['chosen_certs'])) ?> 
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['chosen_certs'] as $certification) {
                                                echo "<li>$certification</li>";
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    <?php } ?>
                                    
                                    <tr><td class='clickable'>
                                        <?= $filterInfo['chosen_groups_category'] ?>
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['chosen_groups'] as $group) {
                                                echo "<li>$group</li>";
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    
                                    <tr><td><?= $filterInfo['chosen_grad_date'] ?></td></tr>
                                    
                                    <?php if ($filterInfo['all_chosen_students']) { ?>
                                    <tr><td>All students matching above criteria</td></tr>
                                    <?php } else { ?>
                                    <tr><td class='clickable'>
                                        <?= count($filterInfo['chosen_students']) ?> <?= Util_String::pluralize("student", count($filterInfo['chosen_students'])) ?>  matching above criteria
                                        <img src='/images/icons/plus.png' class='show-specific-item clickable'>
                                            <ul class='specific-filter'>
                                            <?php foreach($filterInfo['chosen_students'] as $student) {
                                                echo "<li>$student</li>";
                                            } ?>
                                            </ul>
                                    </td></tr>
                                    <?php } ?>
                                    
                                </table>
                                <?php } ?>
                            </td>
                            
                            
                        </tr>
                    </table>
                    
                    <?= ($recurring_email->filter->view_type->name == "month-details") ? "<span class='emails_display_options'><b>Display options: </b> " . $recurring_email->filter->getDisplayOptionDescription() . "</span>": "" ?>

                </div>
            </div>
    <? endforeach; ?>
    
        </div>

<?php else: ?>
        <div>
            Your program has not set up any recurring schedule emails. Visit the schedule to set one up.
        </div>
<?php endif; ?>

    </div>
</div>

<?= $this->schedulerPdfModal; ?>
<div id='deleteRecurringEmailDialog'></div>
