<div class='info'>
    <div class='blue-button' style='float:right;'>
        <input id='close-button' style='padding: 3px 10px;' type='button' value='Close' onclick='window.close()'>
    </div>
    This is a preview of the narrative page your students will see when they type in their Patient Contact data.<br />
    Click <span style="font-weight:bold">Close</span> to finish building your custom narrative format.
</div>

<div class="island grid_12">
<?php echo $this->narrativeForm ?>
</div>