<div id="errorsContainer"></div>

<p>Based on this url, you are resetting the password for <?= $this->element->user->username;?>'s account.</p>
<p>Your new password must be at least five characters long.</p><br/ >

<div class="elementContainer">
    <?= $this->element->newPassword;?>
</div>

<div id="clear"></div>

<div class="elementContainer">
    <?= $this->element->new2;?>
</div>

<div style="clear:both"></div>
<div id="saveButton"><?= $this->element->save;?></div>
<div style="clear:both"></div>

