<div class="grid_12">
	<?= $this->element->emails ?>
</div>

<div class="clear"></div>

<div class="grid_12">
	<?= $this->element->message ?>
</div>

<div class="clear"></div>

<div class="grid_12">
	<?= $this->element->ccSelf ?>
</div>

<div class="clear"></div>

<div class="grid_12">
	<a href="#" id="preview-email">Preview Email</a>
	<div id="preview-email-container"></div>
</div>

<?= $this->element->productCode ?>