<div id="wrapper">
    <div id="formContainer">

        <h3 class="section-header">Confirm your email address</h3>

        <div>To set up an account, you'll need an active email address.</div>

        <?= $this->element->email; ?>

        <div class="withTopMargin">
            <div id="saveButton" class="action-buttons">
                <?= $this->element->save; ?>
            </div>
            <div style="clear:both"></div>
        </div>

    </div>
</div>

