<div id="wrapper">
    <div id="formContainer">
        
        <div class="user_id">
            <?= $this->element->userId;?>
            <img id="throbber" src="/images/throbber_small.gif">
        </div>
        
        <div class="clear"></div>

        <div class="grid_2"></div>
        
        <div class="grid_10">
            <div id="userDetails">
            
            </div>
        </div>

                
        <div class="clear"></div>
        <?= $this->element->program;?>
        
        <div class="clear"></div>
        <div class="grid_12"><?= $this->element->save;?></div>
        

    
    </div>
</div>

