<div class="container_12">
	<?= $this->element->displayErrors() ?>
	
	<div class="grid_12">
		<?php echo $this->element->ivPerformed ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->ivProcedure ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->ivSize ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->site ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->fluid ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->ivAttempts ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->ivSuccess ?>
	</div>
    
    <div class="grid_12">
        <?= $this->element->save ?>
    </div>
	
	<?php echo $this->element->ivId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>