<div class="container_12">
	<?= $this->element->displayErrors() ?>
	
	<div class="grid_12">
		<?php echo $this->element->performed ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->bp ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->pulse ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->respirations ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->spo2 ?>
	</div>
	
	<div class="grid_12">
		<a href="#" id="more-vitals-link">More</a>
	</div>
	<div id="more-vitals" style="display:none;">
		
		<div class="grid_6">
			<?php echo $this->element->skin ?>
		</div>
		
		<div class="grid_6">
			<?php echo $this->element->pupils ?>
		</div>
	
		<div class="clear"></div>
		
		<div class="grid_6">
			<?php echo $this->element->lungSounds ?>
		</div>
		
		<div class="grid_6">
			<?php echo $this->element->bloodGlucose ?>
			<?php echo $this->element->apgar ?>
			<?php echo $this->element->gcs ?>
		</div>
	
	</div>
    
    <div class="prefix_10 grid_2">
        <?= $this->element->save ?>
    </div>
		
	<?php echo $this->element->hiddenId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>