<div class="container_12">
	<?= $this->element->displayErrors() ?>

	<div class="grid_12">
		<?php echo $this->element->medPerformed ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->medication ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->dose ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->route ?>
	</div>
	
	<div class="grid_12">
        <?= $this->element->save ?>
    </div>
	
	<?php echo $this->element->medId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>