<div class="container_12">
	<?= $this->element->displayErrors() ?>
	
	<div class="grid_12">
		<?php echo $this->element->airwayPerformed ?>
	</div>
		
	<div class="grid_12">
		<?php echo $this->element->airwayProcedure ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->airwaySize ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->airwayAttempts ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->airwaySuccess ?>
	</div>
    
    <div class="grid_12">
        <?= $this->element->save ?>
    </div>
	
	<?php echo $this->element->airwayId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>