<div class="container_12">
	<?= $this->element->displayErrors() ?>
	
	<div class="grid_12">
		<?php echo $this->element->rhythmPerformed ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->rhythm . $this->element->twelveLead ?>
	</div>

	<div class="grid_12">
		<?php echo $this->element->ectopies ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->cardiacPerformed ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->cardiacProcedure ?>
	</div>
	
	<div class="grid_12">
		<?php echo $this->element->procedureMethod ?>
		<?php echo $this->element->pacingMethod ?>
	</div>
    
    <div class="grid_12">
        <?= $this->element->save ?>
    </div>
	
	<?php echo $this->element->cardiacId ?>
	<?php echo $this->element->patientId ?>
	<?php echo $this->element->shiftId ?>

</div>