<?php

/* * **************************************************************************
 *
 *         Copyright (C) 1996-2011.  This is an unpublished work of
 *                          Headwaters Software, Inc.
 *                             ALL RIGHTS RESERVED
 *         This program is a trade secret of Headwaters Software, Inc.
 *         and it is not to be copied, distributed, reproduced, published,
 *         or adapted without prior authorization
 *         of Headwaters Software, Inc.
 *
 * ************************************************************************** */

/**
 * Description of test
 *
 * @author astevenson
 */
?>

<?php echo $this->studentPicker($this->studentId, '/portfolio/index/about/studentId/'); ?>

<script>
	$(function(){
		$('#student-list').change(function(){
			alert('lol');
		});
	});
</script>
